// ============================================================================
// PAST TRADING - S&P 500 Asset Definitions with Category Classification
// ============================================================================

// Full S&P 500 stocks categorized by sector (500 stocks total)
const SP500_ASSETS = [
  // ========== TECHNOLOGY (70 stocks) ==========
  { ticker: 'AAPL', name: 'Apple Inc.', basePrice: 150, category: 'tech' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', basePrice: 350, category: 'tech' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', basePrice: 140, category: 'tech' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', basePrice: 141, category: 'tech' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', basePrice: 400, category: 'tech' },
  { ticker: 'META', name: 'Meta Platforms Inc.', basePrice: 330, category: 'tech' },
  { ticker: 'TSLA', name: 'Tesla Inc.', basePrice: 250, category: 'tech' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', basePrice: 850, category: 'tech' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', basePrice: 50, category: 'tech' },
  { ticker: 'ACN', name: 'Accenture plc', basePrice: 340, category: 'tech' },
  { ticker: 'ADBE', name: 'Adobe Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'CRM', name: 'Salesforce Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'INTC', name: 'Intel Corporation', basePrice: 35, category: 'tech' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', basePrice: 135, category: 'tech' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', basePrice: 140, category: 'tech' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', basePrice: 175, category: 'tech' },
  { ticker: 'ORCL', name: 'Oracle Corporation', basePrice: 105, category: 'tech' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', basePrice: 640, category: 'tech' },
  { ticker: 'IBM', name: 'International Business Machines', basePrice: 145, category: 'tech' },
  { ticker: 'INTU', name: 'Intuit Inc.', basePrice: 580, category: 'tech' },
  { ticker: 'AMAT', name: 'Applied Materials Inc.', basePrice: 155, category: 'tech' },
  { ticker: 'MU', name: 'Micron Technology Inc.', basePrice: 88, category: 'tech' },
  { ticker: 'ADI', name: 'Analog Devices Inc.', basePrice: 210, category: 'tech' },
  { ticker: 'LRCX', name: 'Lam Research Corporation', basePrice: 760, category: 'tech' },
  { ticker: 'KLAC', name: 'KLA Corporation', basePrice: 560, category: 'tech' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'CDNS', name: 'Cadence Design Systems', basePrice: 285, category: 'tech' },
  { ticker: 'PANW', name: 'Palo Alto Networks Inc.', basePrice: 280, category: 'tech' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'ADSK', name: 'Autodesk Inc.', basePrice: 250, category: 'tech' },
  { ticker: 'MSCI', name: 'MSCI Inc.', basePrice: 510, category: 'tech' },
  { ticker: 'ROP', name: 'Roper Technologies Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', basePrice: 65, category: 'tech' },
  { ticker: 'MCHP', name: 'Microchip Technology Inc.', basePrice: 85, category: 'tech' },
  { ticker: 'HPQ', name: 'HP Inc.', basePrice: 32, category: 'tech' },
  { ticker: 'NTAP', name: 'NetApp Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'TEAM', name: 'Atlassian Corporation', basePrice: 180, category: 'tech' },
  { ticker: 'WDAY', name: 'Workday Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'ZS', name: 'Zscaler Inc.', basePrice: 190, category: 'tech' },
  { ticker: 'DDOG', name: 'Datadog Inc.', basePrice: 115, category: 'tech' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', basePrice: 160, category: 'tech' },
  { ticker: 'NET', name: 'Cloudflare Inc.', basePrice: 85, category: 'tech' },
  { ticker: 'AKAM', name: 'Akamai Technologies', basePrice: 95, category: 'tech' },
  { ticker: 'VRSN', name: 'VeriSign Inc.', basePrice: 210, category: 'tech' },
  { ticker: 'JNPR', name: 'Juniper Networks Inc.', basePrice: 37, category: 'tech' },
  { ticker: 'FFIV', name: 'F5 Inc.', basePrice: 185, category: 'tech' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'ENPH', name: 'Enphase Energy Inc.', basePrice: 115, category: 'tech' },
  { ticker: 'ON', name: 'ON Semiconductor Corporation', basePrice: 75, category: 'tech' },
  { ticker: 'SMCI', name: 'Super Micro Computer Inc.', basePrice: 320, category: 'tech' },
  { ticker: 'DELL', name: 'Dell Technologies Inc.', basePrice: 75, category: 'tech' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', basePrice: 19, category: 'tech' },
  { ticker: 'WDC', name: 'Western Digital Corporation', basePrice: 58, category: 'tech' },
  { ticker: 'STX', name: 'Seagate Technology Holdings', basePrice: 90, category: 'tech' },
  { ticker: 'NXPI', name: 'NXP Semiconductors NV', basePrice: 225, category: 'tech' },
  { ticker: 'MRVL', name: 'Marvell Technology Inc.', basePrice: 72, category: 'tech' },
  { ticker: 'SWKS', name: 'Skyworks Solutions Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'QRVO', name: 'Qorvo Inc.', basePrice: 105, category: 'tech' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems', basePrice: 540, category: 'tech' },
  { ticker: 'FSLR', name: 'First Solar Inc.', basePrice: 195, category: 'tech' },
  { ticker: 'TER', name: 'Teradyne Inc.', basePrice: 105, category: 'tech' },
  { ticker: 'GLW', name: 'Corning Incorporated', basePrice: 38, category: 'tech' },
  { ticker: 'APH', name: 'Amphenol Corporation', basePrice: 65, category: 'tech' },
  { ticker: 'TYL', name: 'Tyler Technologies Inc.', basePrice: 470, category: 'tech' },
  { ticker: 'ZBRA', name: 'Zebra Technologies Corporation', basePrice: 320, category: 'tech' },
  { ticker: 'KEYS', name: 'Keysight Technologies Inc.', basePrice: 155, category: 'tech' },
  { ticker: 'EPAM', name: 'EPAM Systems Inc.', basePrice: 295, category: 'tech' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', basePrice: 23, category: 'tech' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', basePrice: 25, category: 'tech' },

  // ========== FINANCE (60 stocks) ==========
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', basePrice: 160, category: 'finance' },
  { ticker: 'V', name: 'Visa Inc.', basePrice: 240, category: 'finance' },
  { ticker: 'MA', name: 'Mastercard Inc.', basePrice: 400, category: 'finance' },
  { ticker: 'BAC', name: 'Bank of America Corp.', basePrice: 35, category: 'finance' },
  { ticker: 'WFC', name: 'Wells Fargo & Company', basePrice: 52, category: 'finance' },
  { ticker: 'MS', name: 'Morgan Stanley', basePrice: 95, category: 'finance' },
  { ticker: 'GS', name: 'The Goldman Sachs Group Inc.', basePrice: 390, category: 'finance' },
  { ticker: 'BLK', name: 'BlackRock Inc.', basePrice: 810, category: 'finance' },
  { ticker: 'C', name: 'Citigroup Inc.', basePrice: 58, category: 'finance' },
  { ticker: 'SCHW', name: 'The Charles Schwab Corp.', basePrice: 68, category: 'finance' },
  { ticker: 'AXP', name: 'American Express Company', basePrice: 190, category: 'finance' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', basePrice: 440, category: 'finance' },
  { ticker: 'CB', name: 'Chubb Limited', basePrice: 250, category: 'finance' },
  { ticker: 'PGR', name: 'The Progressive Corporation', basePrice: 175, category: 'finance' },
  { ticker: 'MMC', name: 'Marsh & McLennan Companies', basePrice: 195, category: 'finance' },
  { ticker: 'USB', name: 'U.S. Bancorp', basePrice: 44, category: 'finance' },
  { ticker: 'PNC', name: 'The PNC Financial Services', basePrice: 160, category: 'finance' },
  { ticker: 'AON', name: 'Aon plc', basePrice: 310, category: 'finance' },
  { ticker: 'TFC', name: 'Truist Financial Corporation', basePrice: 40, category: 'finance' },
  { ticker: 'CME', name: 'CME Group Inc.', basePrice: 215, category: 'finance' },
  { ticker: 'ICE', name: 'Intercontinental Exchange', basePrice: 140, category: 'finance' },
  { ticker: 'MCO', name: 'Moody\'s Corporation', basePrice: 360, category: 'finance' },
  { ticker: 'BK', name: 'The Bank of New York Mellon', basePrice: 58, category: 'finance' },
  { ticker: 'AIG', name: 'American International Group', basePrice: 68, category: 'finance' },
  { ticker: 'AFL', name: 'Aflac Incorporated', basePrice: 78, category: 'finance' },
  { ticker: 'ALL', name: 'The Allstate Corporation', basePrice: 145, category: 'finance' },
  { ticker: 'MET', name: 'MetLife Inc.', basePrice: 68, category: 'finance' },
  { ticker: 'PRU', name: 'Prudential Financial Inc.', basePrice: 105, category: 'finance' },
  { ticker: 'TRV', name: 'The Travelers Companies Inc.', basePrice: 195, category: 'finance' },
  { ticker: 'AJG', name: 'Arthur J. Gallagher & Co.', basePrice: 240, category: 'finance' },
  { ticker: 'HIG', name: 'The Hartford Financial Services', basePrice: 88, category: 'finance' },
  { ticker: 'WTW', name: 'Willis Towers Watson', basePrice: 245, category: 'finance' },
  { ticker: 'BRO', name: 'Brown & Brown Inc.', basePrice: 78, category: 'finance' },
  { ticker: 'STT', name: 'State Street Corporation', basePrice: 78, category: 'finance' },
  { ticker: 'TROW', name: 'T. Rowe Price Group Inc.', basePrice: 115, category: 'finance' },
  { ticker: 'BEN', name: 'Franklin Resources Inc.', basePrice: 28, category: 'finance' },
  { ticker: 'IVZ', name: 'Invesco Ltd.', basePrice: 17, category: 'finance' },
  { ticker: 'NTRS', name: 'Northern Trust Corporation', basePrice: 88, category: 'finance' },
  { ticker: 'FIS', name: 'Fidelity National Information', basePrice: 72, category: 'finance' },
  { ticker: 'FISV', name: 'Fiserv Inc.', basePrice: 155, category: 'finance' },
  { ticker: 'DFS', name: 'Discover Financial Services', basePrice: 115, category: 'finance' },
  { ticker: 'SYF', name: 'Synchrony Financial', basePrice: 38, category: 'finance' },
  { ticker: 'COF', name: 'Capital One Financial Corp.', basePrice: 135, category: 'finance' },
  { ticker: 'AMP', name: 'Ameriprise Financial Inc.', basePrice: 385, category: 'finance' },
  { ticker: 'CINF', name: 'Cincinnati Financial Corp.', basePrice: 105, category: 'finance' },
  { ticker: 'L', name: 'Loews Corporation', basePrice: 68, category: 'finance' },
  { ticker: 'PFG', name: 'Principal Financial Group Inc.', basePrice: 78, category: 'finance' },
  { ticker: 'WRB', name: 'W. R. Berkley Corporation', basePrice: 65, category: 'finance' },
  { ticker: 'RE', name: 'Everest Group Ltd.', basePrice: 350, category: 'finance' },
  { ticker: 'GL', name: 'Globe Life Inc.', basePrice: 95, category: 'finance' },
  { ticker: 'RJF', name: 'Raymond James Financial Inc.', basePrice: 115, category: 'finance' },
  { ticker: 'CBOE', name: 'Cboe Global Markets Inc.', basePrice: 175, category: 'finance' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.', basePrice: 62, category: 'finance' },
  { ticker: 'RF', name: 'Regions Financial Corporation', basePrice: 20, category: 'finance' },
  { ticker: 'CFG', name: 'Citizens Financial Group', basePrice: 38, category: 'finance' },
  { ticker: 'KEY', name: 'KeyCorp', basePrice: 15, category: 'finance' },
  { ticker: 'HBAN', name: 'Huntington Bancshares Inc.', basePrice: 14, category: 'finance' },
  { ticker: 'MTB', name: 'M&T Bank Corporation', basePrice: 165, category: 'finance' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', basePrice: 35, category: 'finance' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc.', basePrice: 62, category: 'finance' },

  // ========== HEALTHCARE (80 stocks) ==========
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', basePrice: 510, category: 'healthcare' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', basePrice: 150, category: 'healthcare' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', basePrice: 550, category: 'healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', basePrice: 155, category: 'healthcare' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', basePrice: 540, category: 'healthcare' },
  { ticker: 'ABT', name: 'Abbott Laboratories', basePrice: 110, category: 'healthcare' },
  { ticker: 'DHR', name: 'Danaher Corporation', basePrice: 250, category: 'healthcare' },
  { ticker: 'PFE', name: 'Pfizer Inc.', basePrice: 30, category: 'healthcare' },
  { ticker: 'BMY', name: 'Bristol Myers Squibb Company', basePrice: 55, category: 'healthcare' },
  { ticker: 'AMGN', name: 'Amgen Inc.', basePrice: 280, category: 'healthcare' },
  { ticker: 'GILD', name: 'Gilead Sciences Inc.', basePrice: 78, category: 'healthcare' },
  { ticker: 'CVS', name: 'CVS Health Corporation', basePrice: 68, category: 'healthcare' },
  { ticker: 'MDT', name: 'Medtronic plc', basePrice: 85, category: 'healthcare' },
  { ticker: 'CI', name: 'The Cigna Group', basePrice: 310, category: 'healthcare' },
  { ticker: 'ISRG', name: 'Intuitive Surgical Inc.', basePrice: 380, category: 'healthcare' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', basePrice: 880, category: 'healthcare' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', basePrice: 420, category: 'healthcare' },
  { ticker: 'BSX', name: 'Boston Scientific Corporation', basePrice: 72, category: 'healthcare' },
  { ticker: 'ELV', name: 'Elevance Health Inc.', basePrice: 485, category: 'healthcare' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', basePrice: 175, category: 'healthcare' },
  { ticker: 'HCA', name: 'HCA Healthcare Inc.', basePrice: 285, category: 'healthcare' },
  { ticker: 'SYK', name: 'Stryker Corporation', basePrice: 330, category: 'healthcare' },
  { ticker: 'MCK', name: 'McKesson Corporation', basePrice: 480, category: 'healthcare' },
  { ticker: 'EW', name: 'Edwards Lifesciences Corp.', basePrice: 78, category: 'healthcare' },
  { ticker: 'HUM', name: 'Humana Inc.', basePrice: 350, category: 'healthcare' },
  { ticker: 'COR', name: 'Cencora Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories Inc.', basePrice: 520, category: 'healthcare' },
  { ticker: 'A', name: 'Agilent Technologies Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'IQV', name: 'IQVIA Holdings Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'RMD', name: 'ResMed Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'DXCM', name: 'DexCom Inc.', basePrice: 85, category: 'healthcare' },
  { ticker: 'ALGN', name: 'Align Technology Inc.', basePrice: 285, category: 'healthcare' },
  { ticker: 'BDX', name: 'Becton Dickinson and Company', basePrice: 245, category: 'healthcare' },
  { ticker: 'CAH', name: 'Cardinal Health Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'MTD', name: 'Mettler-Toledo International', basePrice: 1350, category: 'healthcare' },
  { ticker: 'STE', name: 'STERIS plc', basePrice: 220, category: 'healthcare' },
  { ticker: 'BIIB', name: 'Biogen Inc.', basePrice: 240, category: 'healthcare' },
  { ticker: 'MRNA', name: 'Moderna Inc.', basePrice: 85, category: 'healthcare' },
  { ticker: 'BAX', name: 'Baxter International Inc.', basePrice: 38, category: 'healthcare' },
  { ticker: 'WAT', name: 'Waters Corporation', basePrice: 335, category: 'healthcare' },
  { ticker: 'HOLX', name: 'Hologic Inc.', basePrice: 78, category: 'healthcare' },
  { ticker: 'TECH', name: 'Bio-Techne Corporation', basePrice: 75, category: 'healthcare' },
  { ticker: 'ILMN', name: 'Illumina Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'VTRS', name: 'Viatris Inc.', basePrice: 12, category: 'healthcare' },
  { ticker: 'CRL', name: 'Charles River Laboratories', basePrice: 215, category: 'healthcare' },
  { ticker: 'LH', name: 'Labcorp Holdings Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'DGX', name: 'Quest Diagnostics Inc.', basePrice: 145, category: 'healthcare' },
  { ticker: 'MOH', name: 'Molina Healthcare Inc.', basePrice: 330, category: 'healthcare' },
  { ticker: 'PODD', name: 'Insulet Corporation', basePrice: 220, category: 'healthcare' },
  { ticker: 'TFX', name: 'Teleflex Incorporated', basePrice: 245, category: 'healthcare' },
  { ticker: 'HSIC', name: 'Henry Schein Inc.', basePrice: 75, category: 'healthcare' },
  { ticker: 'INCY', name: 'Incyte Corporation', basePrice: 62, category: 'healthcare' },
  { ticker: 'EXAS', name: 'Exact Sciences Corporation', basePrice: 58, category: 'healthcare' },
  { ticker: 'CTLT', name: 'Catalent Inc.', basePrice: 55, category: 'healthcare' },
  { ticker: 'PKI', name: 'PerkinElmer Inc.', basePrice: 125, category: 'healthcare' },
  { ticker: 'BIO', name: 'Bio-Rad Laboratories Inc.', basePrice: 360, category: 'healthcare' },
  { ticker: 'Jazz', name: 'Jazz Pharmaceuticals plc', basePrice: 125, category: 'healthcare' },
  { ticker: 'EXEL', name: 'Exelixis Inc.', basePrice: 22, category: 'healthcare' },
  { ticker: 'NBIX', name: 'Neurocrine Biosciences Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'ALNY', name: 'Alnylam Pharmaceuticals Inc.', basePrice: 195, category: 'healthcare' },
  { ticker: 'BMRN', name: 'BioMarin Pharmaceutical Inc.', basePrice: 88, category: 'healthcare' },
  { ticker: 'UHS', name: 'Universal Health Services', basePrice: 145, category: 'healthcare' },
  { ticker: 'DVA', name: 'DaVita Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'COO', name: 'The Cooper Companies Inc.', basePrice: 380, category: 'healthcare' },
  { ticker: 'XRAY', name: 'DENTSPLY SIRONA Inc.', basePrice: 38, category: 'healthcare' },
  { ticker: 'SYY', name: 'Sysco Corporation', basePrice: 75, category: 'healthcare' },
  { ticker: 'TNDM', name: 'Tandem Diabetes Care Inc.', basePrice: 42, category: 'healthcare' },
  { ticker: 'UTHR', name: 'United Therapeutics Corp.', basePrice: 285, category: 'healthcare' },
  { ticker: 'RARE', name: 'Ultragenyx Pharmaceutical', basePrice: 48, category: 'healthcare' },
  { ticker: 'IONS', name: 'Ionis Pharmaceuticals Inc.', basePrice: 42, category: 'healthcare' },
  { ticker: 'SRPT', name: 'Sarepta Therapeutics Inc.', basePrice: 95, category: 'healthcare' },
  { ticker: 'NTRA', name: 'Natera Inc.', basePrice: 68, category: 'healthcare' },
  { ticker: 'LEGN', name: 'Legend Biotech Corporation', basePrice: 52, category: 'healthcare' },
  { ticker: 'INSM', name: 'Insmed Incorporated', basePrice: 28, category: 'healthcare' },
  { ticker: 'RGEN', name: 'Repligen Corporation', basePrice: 185, category: 'healthcare' },
  { ticker: 'MEDP', name: 'Medpace Holdings Inc.', basePrice: 285, category: 'healthcare' },

  // ========== CONSUMER STAPLES (80 stocks) ==========
  { ticker: 'WMT', name: 'Walmart Inc.', basePrice: 155, category: 'consumer' },
  { ticker: 'PG', name: 'Procter & Gamble Co.', basePrice: 155, category: 'consumer' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', basePrice: 580, category: 'consumer' },
  { ticker: 'KO', name: 'The Coca-Cola Company', basePrice: 60, category: 'consumer' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', basePrice: 175, category: 'consumer' },
  { ticker: 'PM', name: 'Philip Morris International', basePrice: 95, category: 'consumer' },
  { ticker: 'MCD', name: "McDonald's Corporation", basePrice: 275, category: 'consumer' },
  { ticker: 'NKE', name: 'NIKE Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'MDLZ', name: 'Mondelez International Inc.', basePrice: 72, category: 'consumer' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', basePrice: 88, category: 'consumer' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corporation', basePrice: 135, category: 'consumer' },
  { ticker: 'MO', name: 'Altria Group Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'GIS', name: 'General Mills Inc.', basePrice: 68, category: 'consumer' },
  { ticker: 'STZ', name: 'Constellation Brands Inc.', basePrice: 245, category: 'consumer' },
  { ticker: 'KHC', name: 'The Kraft Heinz Company', basePrice: 38, category: 'consumer' },
  { ticker: 'HSY', name: 'The Hershey Company', basePrice: 195, category: 'consumer' },
  { ticker: 'K', name: 'Kellanova', basePrice: 62, category: 'consumer' },
  { ticker: 'SJM', name: 'The J. M. Smucker Company', basePrice: 125, category: 'consumer' },
  { ticker: 'CLX', name: 'The Clorox Company', basePrice: 145, category: 'consumer' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.', basePrice: 35, category: 'consumer' },
  { ticker: 'MNST', name: 'Monster Beverage Corporation', basePrice: 55, category: 'consumer' },
  { ticker: 'CHD', name: 'Church & Dwight Co. Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'CAG', name: 'Conagra Brands Inc.', basePrice: 32, category: 'consumer' },
  { ticker: 'TSN', name: 'Tyson Foods Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'HRL', name: 'Hormel Foods Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'CPB', name: 'Campbell Soup Company', basePrice: 45, category: 'consumer' },
  { ticker: 'TAP', name: 'Molson Coors Beverage Company', basePrice: 62, category: 'consumer' },
  { ticker: 'BG', name: 'Bunge Global SA', basePrice: 105, category: 'consumer' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'EL', name: 'The Estée Lauder Companies', basePrice: 145, category: 'consumer' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland Company', basePrice: 58, category: 'consumer' },
  { ticker: 'KR', name: 'The Kroger Co.', basePrice: 52, category: 'consumer' },
  { ticker: 'SYY', name: 'Sysco Corporation', basePrice: 75, category: 'consumer' },
  { ticker: 'DG', name: 'Dollar General Corporation', basePrice: 105, category: 'consumer' },
  { ticker: 'DLTR', name: 'Dollar Tree Inc.', basePrice: 88, category: 'consumer' },
  { ticker: 'TGT', name: 'Target Corporation', basePrice: 145, category: 'consumer' },
  { ticker: 'YUM', name: 'Yum! Brands Inc.', basePrice: 135, category: 'consumer' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', basePrice: 95, category: 'consumer' },
  { ticker: 'DPZ', name: 'Domino\'s Pizza Inc.', basePrice: 385, category: 'consumer' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'GPC', name: 'Genuine Parts Company', basePrice: 145, category: 'consumer' },
  { ticker: 'AAP', name: 'Advance Auto Parts Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'AZO', name: 'AutoZone Inc.', basePrice: 2850, category: 'consumer' },
  { ticker: 'ORLY', name: "O'Reilly Automotive Inc.", basePrice: 985, category: 'consumer' },
  { ticker: 'ROST', name: 'Ross Stores Inc.', basePrice: 135, category: 'consumer' },
  { ticker: 'TJX', name: 'The TJX Companies Inc.', basePrice: 95, category: 'consumer' },
  { ticker: 'ULTA', name: 'Ulta Beauty Inc.', basePrice: 385, category: 'consumer' },
  { ticker: 'BBY', name: 'Best Buy Co. Inc.', basePrice: 85, category: 'consumer' },
  { ticker: 'RL', name: 'Ralph Lauren Corporation', basePrice: 145, category: 'consumer' },
  { ticker: 'UAA', name: 'Under Armour Inc. Class A', basePrice: 8, category: 'consumer' },
  { ticker: 'VFC', name: 'V.F. Corporation', basePrice: 18, category: 'consumer' },
  { ticker: 'PVH', name: 'PVH Corp.', basePrice: 88, category: 'consumer' },
  { ticker: 'TPR', name: 'Tapestry Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'WHR', name: 'Whirlpool Corporation', basePrice: 125, category: 'consumer' },
  { ticker: 'NWL', name: 'Newell Brands Inc.', basePrice: 9, category: 'consumer' },
  { ticker: 'HAS', name: 'Hasbro Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'MAT', name: 'Mattel Inc.', basePrice: 18, category: 'consumer' },
  { ticker: 'LVS', name: 'Las Vegas Sands Corp.', basePrice: 48, category: 'consumer' },
  { ticker: 'WYNN', name: 'Wynn Resorts Limited', basePrice: 95, category: 'consumer' },
  { ticker: 'MGM', name: 'MGM Resorts International', basePrice: 42, category: 'consumer' },
  { ticker: 'MAR', name: 'Marriott International Inc.', basePrice: 225, category: 'consumer' },
  { ticker: 'HLT', name: 'Hilton Worldwide Holdings Inc.', basePrice: 195, category: 'consumer' },
  { ticker: 'RCL', name: 'Royal Caribbean Cruises Ltd.', basePrice: 145, category: 'consumer' },
  { ticker: 'CCL', name: 'Carnival Corporation', basePrice: 18, category: 'consumer' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line Holdings', basePrice: 18, category: 'consumer' },
  { ticker: 'F', name: 'Ford Motor Company', basePrice: 12, category: 'consumer' },
  { ticker: 'GM', name: 'General Motors Company', basePrice: 42, category: 'consumer' },
  { ticker: 'BBWI', name: 'Bath & Body Works Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'DRI', name: 'Darden Restaurants Inc.', basePrice: 165, category: 'consumer' },
  { ticker: 'QSR', name: 'Restaurant Brands International', basePrice: 68, category: 'consumer' },
  { ticker: 'WEN', name: "The Wendy's Company", basePrice: 18, category: 'consumer' },
  { ticker: 'TXRH', name: 'Texas Roadhouse Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'BJRI', name: "BJ's Restaurants Inc.", basePrice: 38, category: 'consumer' },
  { ticker: 'BLMN', name: 'Bloomin\' Brands Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'CBRL', name: 'Cracker Barrel Old Country', basePrice: 58, category: 'consumer' },

  // ========== INDUSTRIALS (90 stocks) ==========
  { ticker: 'UNP', name: 'Union Pacific Corporation', basePrice: 220, category: 'industrials' },
  { ticker: 'HON', name: 'Honeywell International Inc.', basePrice: 205, category: 'industrials' },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', basePrice: 160, category: 'industrials' },
  { ticker: 'RTX', name: 'RTX Corporation', basePrice: 95, category: 'industrials' },
  { ticker: 'BA', name: 'The Boeing Company', basePrice: 180, category: 'industrials' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', basePrice: 300, category: 'industrials' },
  { ticker: 'GE', name: 'GE Aerospace', basePrice: 145, category: 'industrials' },
  { ticker: 'DE', name: 'Deere & Company', basePrice: 385, category: 'industrials' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation', basePrice: 485, category: 'industrials' },
  { ticker: 'MMM', name: '3M Company', basePrice: 105, category: 'industrials' },
  { ticker: 'GD', name: 'General Dynamics Corporation', basePrice: 270, category: 'industrials' },
  { ticker: 'NOC', name: 'Northrop Grumman Corporation', basePrice: 485, category: 'industrials' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', basePrice: 105, category: 'industrials' },
  { ticker: 'ITW', name: 'Illinois Tool Works Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'ETN', name: 'Eaton Corporation plc', basePrice: 285, category: 'industrials' },
  { ticker: 'PH', name: 'Parker-Hannifin Corporation', basePrice: 520, category: 'industrials' },
  { ticker: 'CSX', name: 'CSX Corporation', basePrice: 35, category: 'industrials' },
  { ticker: 'NSC', name: 'Norfolk Southern Corporation', basePrice: 245, category: 'industrials' },
  { ticker: 'FDX', name: 'FedEx Corporation', basePrice: 285, category: 'industrials' },
  { ticker: 'CARR', name: 'Carrier Global Corporation', basePrice: 58, category: 'industrials' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', basePrice: 105, category: 'industrials' },
  { ticker: 'JCI', name: 'Johnson Controls International', basePrice: 68, category: 'industrials' },
  { ticker: 'WM', name: 'Waste Management Inc.', basePrice: 195, category: 'industrials' },
  { ticker: 'TT', name: 'Trane Technologies plc', basePrice: 285, category: 'industrials' },
  { ticker: 'GWW', name: 'W.W. Grainger Inc.', basePrice: 885, category: 'industrials' },
  { ticker: 'CMI', name: 'Cummins Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'OTIS', name: 'Otis Worldwide Corporation', basePrice: 88, category: 'industrials' },
  { ticker: 'FAST', name: 'Fastenal Company', basePrice: 68, category: 'industrials' },
  { ticker: 'VRSK', name: 'Verisk Analytics Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'ODFL', name: 'Old Dominion Freight Line', basePrice: 385, category: 'industrials' },
  { ticker: 'IR', name: 'Ingersoll Rand Inc.', basePrice: 85, category: 'industrials' },
  { ticker: 'CPRT', name: 'Copart Inc.', basePrice: 52, category: 'industrials' },
  { ticker: 'PAYX', name: 'Paychex Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'RSG', name: 'Republic Services Inc.', basePrice: 185, category: 'industrials' },
  { ticker: 'URI', name: 'United Rentals Inc.', basePrice: 685, category: 'industrials' },
  { ticker: 'HUBB', name: 'Hubbell Incorporated', basePrice: 345, category: 'industrials' },
  { ticker: 'DOV', name: 'Dover Corporation', basePrice: 165, category: 'industrials' },
  { ticker: 'AME', name: 'AMETEK Inc.', basePrice: 165, category: 'industrials' },
  { ticker: 'ROK', name: 'Rockwell Automation Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'XYL', name: 'Xylem Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'CHRW', name: 'C.H. Robinson Worldwide Inc.', basePrice: 105, category: 'industrials' },
  { ticker: 'TDG', name: 'TransDigm Group Incorporated', basePrice: 1185, category: 'industrials' },
  { ticker: 'HWM', name: 'Howmet Aerospace Inc.', basePrice: 62, category: 'industrials' },
  { ticker: 'LHX', name: 'L3Harris Technologies Inc.', basePrice: 215, category: 'industrials' },
  { ticker: 'JBHT', name: 'J.B. Hunt Transport Services', basePrice: 185, category: 'industrials' },
  { ticker: 'EXPD', name: 'Expeditors International', basePrice: 125, category: 'industrials' },
  { ticker: 'CTAS', name: 'Cintas Corporation', basePrice: 585, category: 'industrials' },
  { ticker: 'SNA', name: 'Snap-on Incorporated', basePrice: 285, category: 'industrials' },
  { ticker: 'DAL', name: 'Delta Air Lines Inc.', basePrice: 48, category: 'industrials' },
  { ticker: 'UAL', name: 'United Airlines Holdings Inc.', basePrice: 58, category: 'industrials' },
  { ticker: 'AAL', name: 'American Airlines Group Inc.', basePrice: 14, category: 'industrials' },
  { ticker: 'LUV', name: 'Southwest Airlines Co.', basePrice: 32, category: 'industrials' },
  { ticker: 'ALK', name: 'Alaska Air Group Inc.', basePrice: 42, category: 'industrials' },
  { ticker: 'JBLU', name: 'JetBlue Airways Corporation', basePrice: 6, category: 'industrials' },
  { ticker: 'FTV', name: 'Fortive Corporation', basePrice: 78, category: 'industrials' },
  { ticker: 'TDY', name: 'Teledyne Technologies Inc.', basePrice: 445, category: 'industrials' },
  { ticker: 'LDOS', name: 'Leidos Holdings Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'PWR', name: 'Quanta Services Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'J', name: 'Jacobs Solutions Inc.', basePrice: 135, category: 'industrials' },
  { ticker: 'GPN', name: 'Global Payments Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'TXT', name: 'Textron Inc.', basePrice: 78, category: 'industrials' },
  { ticker: 'AOS', name: 'A. O. Smith Corporation', basePrice: 88, category: 'industrials' },
  { ticker: 'ALLE', name: 'Allegion plc', basePrice: 125, category: 'industrials' },
  { ticker: 'IEX', name: 'IDEX Corporation', basePrice: 215, category: 'industrials' },
  { ticker: 'PNR', name: 'Pentair plc', basePrice: 75, category: 'industrials' },
  { ticker: 'WAB', name: 'Westinghouse Air Brake Tech', basePrice: 145, category: 'industrials' },
  { ticker: 'ROL', name: 'Rollins Inc.', basePrice: 42, category: 'industrials' },
  { ticker: 'GNRC', name: 'Generac Holdings Inc.', basePrice: 135, category: 'industrials' },
  { ticker: 'AIT', name: 'Applied Industrial Technologies', basePrice: 185, category: 'industrials' },
  { ticker: 'BLDR', name: 'Builders FirstSource Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'ALSN', name: 'Allison Transmission Holdings', basePrice: 68, category: 'industrials' },
  { ticker: 'LII', name: 'Lennox International Inc.', basePrice: 485, category: 'industrials' },
  { ticker: 'AXON', name: 'Axon Enterprise Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'MIDD', name: 'The Middleby Corporation', basePrice: 145, category: 'industrials' },
  { ticker: 'VMI', name: 'Valmont Industries Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'RBC', name: 'RBC Bearings Incorporated', basePrice: 285, category: 'industrials' },
  { ticker: 'WWD', name: 'Woodward Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'OSK', name: 'Oshkosh Corporation', basePrice: 105, category: 'industrials' },
  { ticker: 'AGCO', name: 'AGCO Corporation', basePrice: 125, category: 'industrials' },
  { ticker: 'TEX', name: 'Terex Corporation', basePrice: 58, category: 'industrials' },
  { ticker: 'MLM', name: 'Martin Marietta Materials', basePrice: 485, category: 'industrials' },
  { ticker: 'VMC', name: 'Vulcan Materials Company', basePrice: 245, category: 'industrials' },
  { ticker: 'STLD', name: 'Steel Dynamics Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'NUE', name: 'Nucor Corporation', basePrice: 145, category: 'industrials' },
  { ticker: 'RS', name: 'Reliance Steel & Aluminum Co.', basePrice: 285, category: 'industrials' },
  { ticker: 'PKG', name: 'Packaging Corporation of America', basePrice: 185, category: 'industrials' },
  { ticker: 'IP', name: 'International Paper Company', basePrice: 42, category: 'industrials' },
  { ticker: 'WRK', name: 'WestRock Company', basePrice: 48, category: 'industrials' },
  { ticker: 'SEE', name: 'Sealed Air Corporation', basePrice: 38, category: 'industrials' },

  // ========== ENERGY (35 stocks) ==========
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', basePrice: 105, category: 'energy' },
  { ticker: 'CVX', name: 'Chevron Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'COP', name: 'ConocoPhillips', basePrice: 125, category: 'energy' },
  { ticker: 'SLB', name: 'Schlumberger NV', basePrice: 52, category: 'energy' },
  { ticker: 'EOG', name: 'EOG Resources Inc.', basePrice: 125, category: 'energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum Corporation', basePrice: 165, category: 'energy' },
  { ticker: 'PSX', name: 'Phillips 66', basePrice: 145, category: 'energy' },
  { ticker: 'VLO', name: 'Valero Energy Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'OXY', name: 'Occidental Petroleum Corp.', basePrice: 58, category: 'energy' },
  { ticker: 'KMI', name: 'Kinder Morgan Inc.', basePrice: 18, category: 'energy' },
  { ticker: 'WMB', name: 'The Williams Companies Inc.', basePrice: 38, category: 'energy' },
  { ticker: 'HES', name: 'Hess Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'HAL', name: 'Halliburton Company', basePrice: 38, category: 'energy' },
  { ticker: 'BKR', name: 'Baker Hughes Company', basePrice: 32, category: 'energy' },
  { ticker: 'FANG', name: 'Diamondback Energy Inc.', basePrice: 185, category: 'energy' },
  { ticker: 'DVN', name: 'Devon Energy Corporation', basePrice: 48, category: 'energy' },
  { ticker: 'EQT', name: 'EQT Corporation', basePrice: 38, category: 'energy' },
  { ticker: 'TRGP', name: 'Targa Resources Corp.', basePrice: 125, category: 'energy' },
  { ticker: 'MRO', name: 'Marathon Oil Corporation', basePrice: 28, category: 'energy' },
  { ticker: 'APA', name: 'APA Corporation', basePrice: 38, category: 'energy' },
  { ticker: 'CTRA', name: 'Coterra Energy Inc.', basePrice: 28, category: 'energy' },
  { ticker: 'OKE', name: 'ONEOK Inc.', basePrice: 78, category: 'energy' },
  { ticker: 'LNG', name: 'Cheniere Energy Inc.', basePrice: 165, category: 'energy' },
  { ticker: 'VET', name: 'Vermilion Energy Inc.', basePrice: 12, category: 'energy' },
  { ticker: 'APC', name: 'Anadarko Petroleum Corporation', basePrice: 75, category: 'energy' },
  { ticker: 'NOV', name: 'NOV Inc.', basePrice: 18, category: 'energy' },
  { ticker: 'FTI', name: 'TechnipFMC plc', basePrice: 22, category: 'energy' },
  { ticker: 'CHK', name: 'Chesapeake Energy Corporation', basePrice: 88, category: 'energy' },
  { ticker: 'AR', name: 'Antero Resources Corporation', basePrice: 28, category: 'energy' },
  { ticker: 'MGY', name: 'Magnolia Oil & Gas Corporation', basePrice: 24, category: 'energy' },
  { ticker: 'PR', name: 'Permian Resources Corporation', basePrice: 14, category: 'energy' },
  { ticker: 'SM', name: 'SM Energy Company', basePrice: 42, category: 'energy' },
  { ticker: 'RRC', name: 'Range Resources Corporation', basePrice: 32, category: 'energy' },
  { ticker: 'MTDR', name: 'Matador Resources Company', basePrice: 58, category: 'energy' },
  { ticker: 'CHRD', name: 'Chord Energy Corporation', basePrice: 165, category: 'energy' },

  // ========== UTILITIES (30 stocks) ==========
  { ticker: 'NEE', name: 'NextEra Energy Inc.', basePrice: 70, category: 'utilities' },
  { ticker: 'DUK', name: 'Duke Energy Corporation', basePrice: 105, category: 'utilities' },
  { ticker: 'SO', name: 'The Southern Company', basePrice: 82, category: 'utilities' },
  { ticker: 'D', name: 'Dominion Energy Inc.', basePrice: 52, category: 'utilities' },
  { ticker: 'AEP', name: 'American Electric Power Co.', basePrice: 95, category: 'utilities' },
  { ticker: 'EXC', name: 'Exelon Corporation', basePrice: 38, category: 'utilities' },
  { ticker: 'SRE', name: 'Sempra', basePrice: 78, category: 'utilities' },
  { ticker: 'XEL', name: 'Xcel Energy Inc.', basePrice: 62, category: 'utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group Inc.', basePrice: 95, category: 'utilities' },
  { ticker: 'ED', name: 'Consolidated Edison Inc.', basePrice: 95, category: 'utilities' },
  { ticker: 'EIX', name: 'Edison International', basePrice: 75, category: 'utilities' },
  { ticker: 'AWK', name: 'American Water Works Company', basePrice: 145, category: 'utilities' },
  { ticker: 'DTE', name: 'DTE Energy Company', basePrice: 115, category: 'utilities' },
  { ticker: 'PPL', name: 'PPL Corporation', basePrice: 30, category: 'utilities' },
  { ticker: 'ES', name: 'Eversource Energy', basePrice: 62, category: 'utilities' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', basePrice: 38, category: 'utilities' },
  { ticker: 'AEE', name: 'Ameren Corporation', basePrice: 85, category: 'utilities' },
  { ticker: 'CMS', name: 'CMS Energy Corporation', basePrice: 62, category: 'utilities' },
  { ticker: 'PEG', name: 'Public Service Enterprise Group', basePrice: 68, category: 'utilities' },
  { ticker: 'ATO', name: 'Atmos Energy Corporation', basePrice: 125, category: 'utilities' },
  { ticker: 'CNP', name: 'CenterPoint Energy Inc.', basePrice: 32, category: 'utilities' },
  { ticker: 'NI', name: 'NiSource Inc.', basePrice: 30, category: 'utilities' },
  { ticker: 'LNT', name: 'Alliant Energy Corporation', basePrice: 58, category: 'utilities' },
  { ticker: 'EVRG', name: 'Evergy Inc.', basePrice: 58, category: 'utilities' },
  { ticker: 'PNW', name: 'Pinnacle West Capital Corp.', basePrice: 82, category: 'utilities' },
  { ticker: 'AES', name: 'The AES Corporation', basePrice: 18, category: 'utilities' },
  { ticker: 'VST', name: 'Vistra Corp.', basePrice: 85, category: 'utilities' },
  { ticker: 'CEG', name: 'Constellation Energy Corporation', basePrice: 185, category: 'utilities' },
  { ticker: 'PCG', name: 'PG&E Corporation', basePrice: 18, category: 'utilities' },
  { ticker: 'ETR', name: 'Entergy Corporation', basePrice: 115, category: 'utilities' },

  // ========== MEME STOCKS (10 stocks) ==========
  { ticker: 'GME', name: 'GameStop Corp.', basePrice: 20, category: 'meme' },
  { ticker: 'AMC', name: 'AMC Entertainment Holdings', basePrice: 5, category: 'meme' },
  { ticker: 'BB', name: 'BlackBerry Limited', basePrice: 4, category: 'meme' },
  { ticker: 'NOK', name: 'Nokia Corporation', basePrice: 4, category: 'meme' },
  { ticker: 'BBBY', name: 'Bed Bath & Beyond', basePrice: 1, category: 'meme' },
  { ticker: 'CLOV', name: 'Clover Health Investments', basePrice: 2, category: 'meme' },
  { ticker: 'PLUG', name: 'Plug Power Inc.', basePrice: 3, category: 'meme' },
  { ticker: 'RIVN', name: 'Rivian Automotive Inc.', basePrice: 15, category: 'meme' },
  { ticker: 'LCID', name: 'Lucid Group Inc.', basePrice: 3, category: 'meme' },
];
