// ============================================================================
// PAST TRADING - S&P 500 Asset Definitions
// ============================================================================

// Top 50 S&P 500 stocks by market cap (expandable to full 500)
const SP500_ASSETS = [
  { ticker: 'AAPL', name: 'Apple Inc.', basePrice: 150 },
  { ticker: 'MSFT', name: 'Microsoft Corporation', basePrice: 350 },
  { ticker: 'GOOGL', name: 'Alphabet Inc.', basePrice: 140 },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', basePrice: 145 },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', basePrice: 400 },
  { ticker: 'META', name: 'Meta Platforms Inc.', basePrice: 330 },
  { ticker: 'TSLA', name: 'Tesla Inc.', basePrice: 250 },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.', basePrice: 380 },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', basePrice: 160 },
  { ticker: 'JNJ', name: 'Johnson & Johnson', basePrice: 150 },
  { ticker: 'V', name: 'Visa Inc.', basePrice: 240 },
  { ticker: 'PG', name: 'Procter & Gamble Co.', basePrice: 155 },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', basePrice: 105 },
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', basePrice: 510 },
  { ticker: 'MA', name: 'Mastercard Inc.', basePrice: 400 },
  { ticker: 'HD', name: 'The Home Depot Inc.', basePrice: 310 },
  { ticker: 'CVX', name: 'Chevron Corporation', basePrice: 145 },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', basePrice: 105 },
  { ticker: 'ABBV', name: 'AbbVie Inc.', basePrice: 155 },
  { ticker: 'PFE', name: 'Pfizer Inc.', basePrice: 30 },
  { ticker: 'KO', name: 'The Coca-Cola Company', basePrice: 60 },
  { ticker: 'PEP', name: 'PepsiCo Inc.', basePrice: 175 },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', basePrice: 580 },
  { ticker: 'AVGO', name: 'Broadcom Inc.', basePrice: 850 },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', basePrice: 540 },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', basePrice: 50 },
  { ticker: 'ACN', name: 'Accenture plc', basePrice: 340 },
  { ticker: 'WMT', name: 'Walmart Inc.', basePrice: 155 },
  { ticker: 'DIS', name: 'The Walt Disney Company', basePrice: 95 },
  { ticker: 'NFLX', name: 'Netflix Inc.', basePrice: 450 },
  { ticker: 'ADBE', name: 'Adobe Inc.', basePrice: 520 },
  { ticker: 'CRM', name: 'Salesforce Inc.', basePrice: 240 },
  { ticker: 'ABT', name: 'Abbott Laboratories', basePrice: 110 },
  { ticker: 'NKE', name: 'NIKE Inc.', basePrice: 105 },
  { ticker: 'MCD', name: "McDonald's Corporation", basePrice: 275 },
  { ticker: 'LLY', name: 'Eli Lilly and Company', basePrice: 550 },
  { ticker: 'INTC', name: 'Intel Corporation', basePrice: 35 },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', basePrice: 135 },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', basePrice: 140 },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', basePrice: 175 },
  { ticker: 'DHR', name: 'Danaher Corporation', basePrice: 250 },
  { ticker: 'PM', name: 'Philip Morris International Inc.', basePrice: 95 },
  { ticker: 'UNP', name: 'Union Pacific Corporation', basePrice: 220 },
  { ticker: 'NEE', name: 'NextEra Energy Inc.', basePrice: 70 },
  { ticker: 'BMY', name: 'Bristol Myers Squibb Company', basePrice: 55 },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', basePrice: 160 },
  { ticker: 'LOW', name: "Lowe's Companies Inc.", basePrice: 215 },
  { ticker: 'RTX', name: 'RTX Corporation', basePrice: 95 },
  { ticker: 'AMGN', name: 'Amgen Inc.', basePrice: 280 },
  { ticker: 'HON', name: 'Honeywell International Inc.', basePrice: 205 }
];
