// ============================================================================
// PAST TRADING - S&P 500 Asset Definitions with Category Classification
// ============================================================================

// Full S&P 500 stocks categorized by sector (500 stocks total)
const SP500_ASSETS = [
  // ========== TECHNOLOGY (70 stocks) ==========
  { ticker: 'AAPL', name: 'Apple Inc.', basePrice: 150, category: 'tech' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', basePrice: 350, category: 'tech' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', basePrice: 140, category: 'tech' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', basePrice: 141, category: 'tech' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', basePrice: 400, category: 'tech' },
  { ticker: 'META', name: 'Meta Platforms Inc.', basePrice: 330, category: 'tech' },
  { ticker: 'TSLA', name: 'Tesla Inc.', basePrice: 250, category: 'tech' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', basePrice: 850, category: 'tech' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', basePrice: 50, category: 'tech' },
  { ticker: 'ACN', name: 'Accenture plc', basePrice: 340, category: 'tech' },
  { ticker: 'ADBE', name: 'Adobe Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'CRM', name: 'Salesforce Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'INTC', name: 'Intel Corporation', basePrice: 35, category: 'tech' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', basePrice: 135, category: 'tech' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', basePrice: 140, category: 'tech' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', basePrice: 175, category: 'tech' },
  { ticker: 'ORCL', name: 'Oracle Corporation', basePrice: 105, category: 'tech' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', basePrice: 640, category: 'tech' },
  { ticker: 'IBM', name: 'International Business Machines', basePrice: 145, category: 'tech' },
  { ticker: 'INTU', name: 'Intuit Inc.', basePrice: 580, category: 'tech' },
  { ticker: 'AMAT', name: 'Applied Materials Inc.', basePrice: 155, category: 'tech' },
  { ticker: 'MU', name: 'Micron Technology Inc.', basePrice: 88, category: 'tech' },
  { ticker: 'ADI', name: 'Analog Devices Inc.', basePrice: 210, category: 'tech' },
  { ticker: 'LRCX', name: 'Lam Research Corporation', basePrice: 760, category: 'tech' },
  { ticker: 'KLAC', name: 'KLA Corporation', basePrice: 560, category: 'tech' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'CDNS', name: 'Cadence Design Systems', basePrice: 285, category: 'tech' },
  { ticker: 'PANW', name: 'Palo Alto Networks Inc.', basePrice: 280, category: 'tech' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'ADSK', name: 'Autodesk Inc.', basePrice: 250, category: 'tech' },
  { ticker: 'MSCI', name: 'MSCI Inc.', basePrice: 510, category: 'tech' },
  { ticker: 'ROP', name: 'Roper Technologies Inc.', basePrice: 520, category: 'tech' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', basePrice: 65, category: 'tech' },
  { ticker: 'MCHP', name: 'Microchip Technology Inc.', basePrice: 85, category: 'tech' },
  { ticker: 'HPQ', name: 'HP Inc.', basePrice: 32, category: 'tech' },
  { ticker: 'NTAP', name: 'NetApp Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'TEAM', name: 'Atlassian Corporation', basePrice: 180, category: 'tech' },
  { ticker: 'WDAY', name: 'Workday Inc.', basePrice: 240, category: 'tech' },
  { ticker: 'ZS', name: 'Zscaler Inc.', basePrice: 190, category: 'tech' },
  { ticker: 'DDOG', name: 'Datadog Inc.', basePrice: 115, category: 'tech' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', basePrice: 160, category: 'tech' },
  { ticker: 'NET', name: 'Cloudflare Inc.', basePrice: 85, category: 'tech' },
  { ticker: 'AKAM', name: 'Akamai Technologies', basePrice: 95, category: 'tech' },
  { ticker: 'VRSN', name: 'VeriSign Inc.', basePrice: 210, category: 'tech' },
  { ticker: 'JNPR', name: 'Juniper Networks Inc.', basePrice: 37, category: 'tech' },
  { ticker: 'FFIV', name: 'F5 Inc.', basePrice: 185, category: 'tech' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'ENPH', name: 'Enphase Energy Inc.', basePrice: 115, category: 'tech' },
  { ticker: 'ON', name: 'ON Semiconductor Corporation', basePrice: 75, category: 'tech' },
  { ticker: 'SMCI', name: 'Super Micro Computer Inc.', basePrice: 320, category: 'tech' },
  { ticker: 'DELL', name: 'Dell Technologies Inc.', basePrice: 75, category: 'tech' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', basePrice: 19, category: 'tech' },
  { ticker: 'WDC', name: 'Western Digital Corporation', basePrice: 58, category: 'tech' },
  { ticker: 'STX', name: 'Seagate Technology Holdings', basePrice: 90, category: 'tech' },
  { ticker: 'NXPI', name: 'NXP Semiconductors NV', basePrice: 225, category: 'tech' },
  { ticker: 'MRVL', name: 'Marvell Technology Inc.', basePrice: 72, category: 'tech' },
  { ticker: 'SWKS', name: 'Skyworks Solutions Inc.', basePrice: 95, category: 'tech' },
  { ticker: 'QRVO', name: 'Qorvo Inc.', basePrice: 105, category: 'tech' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems', basePrice: 540, category: 'tech' },
  { ticker: 'FSLR', name: 'First Solar Inc.', basePrice: 195, category: 'tech' },
  { ticker: 'TER', name: 'Teradyne Inc.', basePrice: 105, category: 'tech' },
  { ticker: 'GLW', name: 'Corning Incorporated', basePrice: 38, category: 'tech' },
  { ticker: 'APH', name: 'Amphenol Corporation', basePrice: 65, category: 'tech' },
  { ticker: 'TYL', name: 'Tyler Technologies Inc.', basePrice: 470, category: 'tech' },
  { ticker: 'ZBRA', name: 'Zebra Technologies Corporation', basePrice: 320, category: 'tech' },
  { ticker: 'KEYS', name: 'Keysight Technologies Inc.', basePrice: 155, category: 'tech' },
  { ticker: 'EPAM', name: 'EPAM Systems Inc.', basePrice: 295, category: 'tech' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', basePrice: 23, category: 'tech' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', basePrice: 25, category: 'tech' },

  // ========== FINANCE (60 stocks) ==========
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', basePrice: 160, category: 'finance' },
  { ticker: 'V', name: 'Visa Inc.', basePrice: 240, category: 'finance' },
  { ticker: 'MA', name: 'Mastercard Inc.', basePrice: 400, category: 'finance' },
  { ticker: 'BAC', name: 'Bank of America Corp.', basePrice: 35, category: 'finance' },
  { ticker: 'WFC', name: 'Wells Fargo & Company', basePrice: 52, category: 'finance' },
  { ticker: 'MS', name: 'Morgan Stanley', basePrice: 95, category: 'finance' },
  { ticker: 'GS', name: 'The Goldman Sachs Group Inc.', basePrice: 390, category: 'finance' },
  { ticker: 'BLK', name: 'BlackRock Inc.', basePrice: 810, category: 'finance' },
  { ticker: 'C', name: 'Citigroup Inc.', basePrice: 58, category: 'finance' },
  { ticker: 'SCHW', name: 'The Charles Schwab Corp.', basePrice: 68, category: 'finance' },
  { ticker: 'AXP', name: 'American Express Company', basePrice: 190, category: 'finance' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', basePrice: 440, category: 'finance' },
  { ticker: 'CB', name: 'Chubb Limited', basePrice: 250, category: 'finance' },
  { ticker: 'PGR', name: 'The Progressive Corporation', basePrice: 175, category: 'finance' },
  { ticker: 'MMC', name: 'Marsh & McLennan Companies', basePrice: 195, category: 'finance' },
  { ticker: 'USB', name: 'U.S. Bancorp', basePrice: 44, category: 'finance' },
  { ticker: 'PNC', name: 'The PNC Financial Services', basePrice: 160, category: 'finance' },
  { ticker: 'AON', name: 'Aon plc', basePrice: 310, category: 'finance' },
  { ticker: 'TFC', name: 'Truist Financial Corporation', basePrice: 40, category: 'finance' },
  { ticker: 'CME', name: 'CME Group Inc.', basePrice: 215, category: 'finance' },
  { ticker: 'ICE', name: 'Intercontinental Exchange', basePrice: 140, category: 'finance' },
  { ticker: 'MCO', name: 'Moody\'s Corporation', basePrice: 360, category: 'finance' },
  { ticker: 'BK', name: 'The Bank of New York Mellon', basePrice: 58, category: 'finance' },
  { ticker: 'AIG', name: 'American International Group', basePrice: 68, category: 'finance' },
  { ticker: 'AFL', name: 'Aflac Incorporated', basePrice: 78, category: 'finance' },
  { ticker: 'ALL', name: 'The Allstate Corporation', basePrice: 145, category: 'finance' },
  { ticker: 'MET', name: 'MetLife Inc.', basePrice: 68, category: 'finance' },
  { ticker: 'PRU', name: 'Prudential Financial Inc.', basePrice: 105, category: 'finance' },
  { ticker: 'TRV', name: 'The Travelers Companies Inc.', basePrice: 195, category: 'finance' },
  { ticker: 'AJG', name: 'Arthur J. Gallagher & Co.', basePrice: 240, category: 'finance' },
  { ticker: 'HIG', name: 'The Hartford Financial Services', basePrice: 88, category: 'finance' },
  { ticker: 'WTW', name: 'Willis Towers Watson', basePrice: 245, category: 'finance' },
  { ticker: 'BRO', name: 'Brown & Brown Inc.', basePrice: 78, category: 'finance' },
  { ticker: 'STT', name: 'State Street Corporation', basePrice: 78, category: 'finance' },
  { ticker: 'TROW', name: 'T. Rowe Price Group Inc.', basePrice: 115, category: 'finance' },
  { ticker: 'BEN', name: 'Franklin Resources Inc.', basePrice: 28, category: 'finance' },
  { ticker: 'IVZ', name: 'Invesco Ltd.', basePrice: 17, category: 'finance' },
  { ticker: 'NTRS', name: 'Northern Trust Corporation', basePrice: 88, category: 'finance' },
  { ticker: 'FIS', name: 'Fidelity National Information', basePrice: 72, category: 'finance' },
  { ticker: 'FISV', name: 'Fiserv Inc.', basePrice: 155, category: 'finance' },
  { ticker: 'DFS', name: 'Discover Financial Services', basePrice: 115, category: 'finance' },
  { ticker: 'SYF', name: 'Synchrony Financial', basePrice: 38, category: 'finance' },
  { ticker: 'COF', name: 'Capital One Financial Corp.', basePrice: 135, category: 'finance' },
  { ticker: 'AMP', name: 'Ameriprise Financial Inc.', basePrice: 385, category: 'finance' },
  { ticker: 'CINF', name: 'Cincinnati Financial Corp.', basePrice: 105, category: 'finance' },
  { ticker: 'L', name: 'Loews Corporation', basePrice: 68, category: 'finance' },
  { ticker: 'PFG', name: 'Principal Financial Group Inc.', basePrice: 78, category: 'finance' },
  { ticker: 'WRB', name: 'W. R. Berkley Corporation', basePrice: 65, category: 'finance' },
  { ticker: 'RE', name: 'Everest Group Ltd.', basePrice: 350, category: 'finance' },
  { ticker: 'GL', name: 'Globe Life Inc.', basePrice: 95, category: 'finance' },
  { ticker: 'RJF', name: 'Raymond James Financial Inc.', basePrice: 115, category: 'finance' },
  { ticker: 'CBOE', name: 'Cboe Global Markets Inc.', basePrice: 175, category: 'finance' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.', basePrice: 62, category: 'finance' },
  { ticker: 'RF', name: 'Regions Financial Corporation', basePrice: 20, category: 'finance' },
  { ticker: 'CFG', name: 'Citizens Financial Group', basePrice: 38, category: 'finance' },
  { ticker: 'KEY', name: 'KeyCorp', basePrice: 15, category: 'finance' },
  { ticker: 'HBAN', name: 'Huntington Bancshares Inc.', basePrice: 14, category: 'finance' },
  { ticker: 'MTB', name: 'M&T Bank Corporation', basePrice: 165, category: 'finance' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', basePrice: 35, category: 'finance' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc.', basePrice: 62, category: 'finance' },

  // ========== HEALTHCARE (80 stocks) ==========
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', basePrice: 510, category: 'healthcare' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', basePrice: 150, category: 'healthcare' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', basePrice: 550, category: 'healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', basePrice: 155, category: 'healthcare' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', basePrice: 540, category: 'healthcare' },
  { ticker: 'ABT', name: 'Abbott Laboratories', basePrice: 110, category: 'healthcare' },
  { ticker: 'DHR', name: 'Danaher Corporation', basePrice: 250, category: 'healthcare' },
  { ticker: 'PFE', name: 'Pfizer Inc.', basePrice: 30, category: 'healthcare' },
  { ticker: 'BMY', name: 'Bristol Myers Squibb Company', basePrice: 55, category: 'healthcare' },
  { ticker: 'AMGN', name: 'Amgen Inc.', basePrice: 280, category: 'healthcare' },
  { ticker: 'GILD', name: 'Gilead Sciences Inc.', basePrice: 78, category: 'healthcare' },
  { ticker: 'CVS', name: 'CVS Health Corporation', basePrice: 68, category: 'healthcare' },
  { ticker: 'MDT', name: 'Medtronic plc', basePrice: 85, category: 'healthcare' },
  { ticker: 'CI', name: 'The Cigna Group', basePrice: 310, category: 'healthcare' },
  { ticker: 'ISRG', name: 'Intuitive Surgical Inc.', basePrice: 380, category: 'healthcare' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', basePrice: 880, category: 'healthcare' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', basePrice: 420, category: 'healthcare' },
  { ticker: 'BSX', name: 'Boston Scientific Corporation', basePrice: 72, category: 'healthcare' },
  { ticker: 'ELV', name: 'Elevance Health Inc.', basePrice: 485, category: 'healthcare' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', basePrice: 175, category: 'healthcare' },
  { ticker: 'HCA', name: 'HCA Healthcare Inc.', basePrice: 285, category: 'healthcare' },
  { ticker: 'SYK', name: 'Stryker Corporation', basePrice: 330, category: 'healthcare' },
  { ticker: 'MCK', name: 'McKesson Corporation', basePrice: 480, category: 'healthcare' },
  { ticker: 'EW', name: 'Edwards Lifesciences Corp.', basePrice: 78, category: 'healthcare' },
  { ticker: 'HUM', name: 'Humana Inc.', basePrice: 350, category: 'healthcare' },
  { ticker: 'COR', name: 'Cencora Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories Inc.', basePrice: 520, category: 'healthcare' },
  { ticker: 'A', name: 'Agilent Technologies Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'IQV', name: 'IQVIA Holdings Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'RMD', name: 'ResMed Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'DXCM', name: 'DexCom Inc.', basePrice: 85, category: 'healthcare' },
  { ticker: 'ALGN', name: 'Align Technology Inc.', basePrice: 285, category: 'healthcare' },
  { ticker: 'BDX', name: 'Becton Dickinson and Company', basePrice: 245, category: 'healthcare' },
  { ticker: 'CAH', name: 'Cardinal Health Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'MTD', name: 'Mettler-Toledo International', basePrice: 1350, category: 'healthcare' },
  { ticker: 'STE', name: 'STERIS plc', basePrice: 220, category: 'healthcare' },
  { ticker: 'BIIB', name: 'Biogen Inc.', basePrice: 240, category: 'healthcare' },
  { ticker: 'MRNA', name: 'Moderna Inc.', basePrice: 85, category: 'healthcare' },
  { ticker: 'BAX', name: 'Baxter International Inc.', basePrice: 38, category: 'healthcare' },
  { ticker: 'WAT', name: 'Waters Corporation', basePrice: 335, category: 'healthcare' },
  { ticker: 'HOLX', name: 'Hologic Inc.', basePrice: 78, category: 'healthcare' },
  { ticker: 'TECH', name: 'Bio-Techne Corporation', basePrice: 75, category: 'healthcare' },
  { ticker: 'ILMN', name: 'Illumina Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'VTRS', name: 'Viatris Inc.', basePrice: 12, category: 'healthcare' },
  { ticker: 'CRL', name: 'Charles River Laboratories', basePrice: 215, category: 'healthcare' },
  { ticker: 'LH', name: 'Labcorp Holdings Inc.', basePrice: 220, category: 'healthcare' },
  { ticker: 'DGX', name: 'Quest Diagnostics Inc.', basePrice: 145, category: 'healthcare' },
  { ticker: 'MOH', name: 'Molina Healthcare Inc.', basePrice: 330, category: 'healthcare' },
  { ticker: 'PODD', name: 'Insulet Corporation', basePrice: 220, category: 'healthcare' },
  { ticker: 'TFX', name: 'Teleflex Incorporated', basePrice: 245, category: 'healthcare' },
  { ticker: 'HSIC', name: 'Henry Schein Inc.', basePrice: 75, category: 'healthcare' },
  { ticker: 'INCY', name: 'Incyte Corporation', basePrice: 62, category: 'healthcare' },
  { ticker: 'EXAS', name: 'Exact Sciences Corporation', basePrice: 58, category: 'healthcare' },
  { ticker: 'CTLT', name: 'Catalent Inc.', basePrice: 55, category: 'healthcare' },
  { ticker: 'PKI', name: 'PerkinElmer Inc.', basePrice: 125, category: 'healthcare' },
  { ticker: 'BIO', name: 'Bio-Rad Laboratories Inc.', basePrice: 360, category: 'healthcare' },
  { ticker: 'Jazz', name: 'Jazz Pharmaceuticals plc', basePrice: 125, category: 'healthcare' },
  { ticker: 'EXEL', name: 'Exelixis Inc.', basePrice: 22, category: 'healthcare' },
  { ticker: 'NBIX', name: 'Neurocrine Biosciences Inc.', basePrice: 135, category: 'healthcare' },
  { ticker: 'ALNY', name: 'Alnylam Pharmaceuticals Inc.', basePrice: 195, category: 'healthcare' },
  { ticker: 'BMRN', name: 'BioMarin Pharmaceutical Inc.', basePrice: 88, category: 'healthcare' },
  { ticker: 'UHS', name: 'Universal Health Services', basePrice: 145, category: 'healthcare' },
  { ticker: 'DVA', name: 'DaVita Inc.', basePrice: 105, category: 'healthcare' },
  { ticker: 'COO', name: 'The Cooper Companies Inc.', basePrice: 380, category: 'healthcare' },
  { ticker: 'XRAY', name: 'DENTSPLY SIRONA Inc.', basePrice: 38, category: 'healthcare' },
  { ticker: 'SYY', name: 'Sysco Corporation', basePrice: 75, category: 'healthcare' },
  { ticker: 'TNDM', name: 'Tandem Diabetes Care Inc.', basePrice: 42, category: 'healthcare' },
  { ticker: 'UTHR', name: 'United Therapeutics Corp.', basePrice: 285, category: 'healthcare' },
  { ticker: 'RARE', name: 'Ultragenyx Pharmaceutical', basePrice: 48, category: 'healthcare' },
  { ticker: 'IONS', name: 'Ionis Pharmaceuticals Inc.', basePrice: 42, category: 'healthcare' },
  { ticker: 'SRPT', name: 'Sarepta Therapeutics Inc.', basePrice: 95, category: 'healthcare' },
  { ticker: 'NTRA', name: 'Natera Inc.', basePrice: 68, category: 'healthcare' },
  { ticker: 'LEGN', name: 'Legend Biotech Corporation', basePrice: 52, category: 'healthcare' },
  { ticker: 'INSM', name: 'Insmed Incorporated', basePrice: 28, category: 'healthcare' },
  { ticker: 'RGEN', name: 'Repligen Corporation', basePrice: 185, category: 'healthcare' },
  { ticker: 'MEDP', name: 'Medpace Holdings Inc.', basePrice: 285, category: 'healthcare' },

  // ========== CONSUMER STAPLES (80 stocks) ==========
  { ticker: 'WMT', name: 'Walmart Inc.', basePrice: 155, category: 'consumer' },
  { ticker: 'PG', name: 'Procter & Gamble Co.', basePrice: 155, category: 'consumer' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', basePrice: 580, category: 'consumer' },
  { ticker: 'KO', name: 'The Coca-Cola Company', basePrice: 60, category: 'consumer' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', basePrice: 175, category: 'consumer' },
  { ticker: 'PM', name: 'Philip Morris International', basePrice: 95, category: 'consumer' },
  { ticker: 'MCD', name: "McDonald's Corporation", basePrice: 275, category: 'consumer' },
  { ticker: 'NKE', name: 'NIKE Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'MDLZ', name: 'Mondelez International Inc.', basePrice: 72, category: 'consumer' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', basePrice: 88, category: 'consumer' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corporation', basePrice: 135, category: 'consumer' },
  { ticker: 'MO', name: 'Altria Group Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'GIS', name: 'General Mills Inc.', basePrice: 68, category: 'consumer' },
  { ticker: 'STZ', name: 'Constellation Brands Inc.', basePrice: 245, category: 'consumer' },
  { ticker: 'KHC', name: 'The Kraft Heinz Company', basePrice: 38, category: 'consumer' },
  { ticker: 'HSY', name: 'The Hershey Company', basePrice: 195, category: 'consumer' },
  { ticker: 'K', name: 'Kellanova', basePrice: 62, category: 'consumer' },
  { ticker: 'SJM', name: 'The J. M. Smucker Company', basePrice: 125, category: 'consumer' },
  { ticker: 'CLX', name: 'The Clorox Company', basePrice: 145, category: 'consumer' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.', basePrice: 35, category: 'consumer' },
  { ticker: 'MNST', name: 'Monster Beverage Corporation', basePrice: 55, category: 'consumer' },
  { ticker: 'CHD', name: 'Church & Dwight Co. Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'CAG', name: 'Conagra Brands Inc.', basePrice: 32, category: 'consumer' },
  { ticker: 'TSN', name: 'Tyson Foods Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'HRL', name: 'Hormel Foods Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'CPB', name: 'Campbell Soup Company', basePrice: 45, category: 'consumer' },
  { ticker: 'TAP', name: 'Molson Coors Beverage Company', basePrice: 62, category: 'consumer' },
  { ticker: 'BG', name: 'Bunge Global SA', basePrice: 105, category: 'consumer' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'EL', name: 'The Estée Lauder Companies', basePrice: 145, category: 'consumer' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland Company', basePrice: 58, category: 'consumer' },
  { ticker: 'KR', name: 'The Kroger Co.', basePrice: 52, category: 'consumer' },
  { ticker: 'SYY', name: 'Sysco Corporation', basePrice: 75, category: 'consumer' },
  { ticker: 'DG', name: 'Dollar General Corporation', basePrice: 105, category: 'consumer' },
  { ticker: 'DLTR', name: 'Dollar Tree Inc.', basePrice: 88, category: 'consumer' },
  { ticker: 'TGT', name: 'Target Corporation', basePrice: 145, category: 'consumer' },
  { ticker: 'YUM', name: 'Yum! Brands Inc.', basePrice: 135, category: 'consumer' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', basePrice: 95, category: 'consumer' },
  { ticker: 'DPZ', name: 'Domino\'s Pizza Inc.', basePrice: 385, category: 'consumer' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', basePrice: 105, category: 'consumer' },
  { ticker: 'GPC', name: 'Genuine Parts Company', basePrice: 145, category: 'consumer' },
  { ticker: 'AAP', name: 'Advance Auto Parts Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'AZO', name: 'AutoZone Inc.', basePrice: 2850, category: 'consumer' },
  { ticker: 'ORLY', name: "O'Reilly Automotive Inc.", basePrice: 985, category: 'consumer' },
  { ticker: 'ROST', name: 'Ross Stores Inc.', basePrice: 135, category: 'consumer' },
  { ticker: 'TJX', name: 'The TJX Companies Inc.', basePrice: 95, category: 'consumer' },
  { ticker: 'ULTA', name: 'Ulta Beauty Inc.', basePrice: 385, category: 'consumer' },
  { ticker: 'BBY', name: 'Best Buy Co. Inc.', basePrice: 85, category: 'consumer' },
  { ticker: 'RL', name: 'Ralph Lauren Corporation', basePrice: 145, category: 'consumer' },
  { ticker: 'UAA', name: 'Under Armour Inc. Class A', basePrice: 8, category: 'consumer' },
  { ticker: 'VFC', name: 'V.F. Corporation', basePrice: 18, category: 'consumer' },
  { ticker: 'PVH', name: 'PVH Corp.', basePrice: 88, category: 'consumer' },
  { ticker: 'TPR', name: 'Tapestry Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'WHR', name: 'Whirlpool Corporation', basePrice: 125, category: 'consumer' },
  { ticker: 'NWL', name: 'Newell Brands Inc.', basePrice: 9, category: 'consumer' },
  { ticker: 'HAS', name: 'Hasbro Inc.', basePrice: 58, category: 'consumer' },
  { ticker: 'MAT', name: 'Mattel Inc.', basePrice: 18, category: 'consumer' },
  { ticker: 'LVS', name: 'Las Vegas Sands Corp.', basePrice: 48, category: 'consumer' },
  { ticker: 'WYNN', name: 'Wynn Resorts Limited', basePrice: 95, category: 'consumer' },
  { ticker: 'MGM', name: 'MGM Resorts International', basePrice: 42, category: 'consumer' },
  { ticker: 'MAR', name: 'Marriott International Inc.', basePrice: 225, category: 'consumer' },
  { ticker: 'HLT', name: 'Hilton Worldwide Holdings Inc.', basePrice: 195, category: 'consumer' },
  { ticker: 'RCL', name: 'Royal Caribbean Cruises Ltd.', basePrice: 145, category: 'consumer' },
  { ticker: 'CCL', name: 'Carnival Corporation', basePrice: 18, category: 'consumer' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line Holdings', basePrice: 18, category: 'consumer' },
  { ticker: 'F', name: 'Ford Motor Company', basePrice: 12, category: 'consumer' },
  { ticker: 'GM', name: 'General Motors Company', basePrice: 42, category: 'consumer' },
  { ticker: 'BBWI', name: 'Bath & Body Works Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'DRI', name: 'Darden Restaurants Inc.', basePrice: 165, category: 'consumer' },
  { ticker: 'QSR', name: 'Restaurant Brands International', basePrice: 68, category: 'consumer' },
  { ticker: 'WEN', name: "The Wendy's Company", basePrice: 18, category: 'consumer' },
  { ticker: 'TXRH', name: 'Texas Roadhouse Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'BJRI', name: "BJ's Restaurants Inc.", basePrice: 38, category: 'consumer' },
  { ticker: 'BLMN', name: 'Bloomin\' Brands Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'CBRL', name: 'Cracker Barrel Old Country', basePrice: 58, category: 'consumer' },

  // ========== INDUSTRIALS (90 stocks) ==========
  { ticker: 'UNP', name: 'Union Pacific Corporation', basePrice: 220, category: 'industrials' },
  { ticker: 'HON', name: 'Honeywell International Inc.', basePrice: 205, category: 'industrials' },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', basePrice: 160, category: 'industrials' },
  { ticker: 'RTX', name: 'RTX Corporation', basePrice: 95, category: 'industrials' },
  { ticker: 'BA', name: 'The Boeing Company', basePrice: 180, category: 'industrials' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', basePrice: 300, category: 'industrials' },
  { ticker: 'GE', name: 'GE Aerospace', basePrice: 145, category: 'industrials' },
  { ticker: 'DE', name: 'Deere & Company', basePrice: 385, category: 'industrials' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation', basePrice: 485, category: 'industrials' },
  { ticker: 'MMM', name: '3M Company', basePrice: 105, category: 'industrials' },
  { ticker: 'GD', name: 'General Dynamics Corporation', basePrice: 270, category: 'industrials' },
  { ticker: 'NOC', name: 'Northrop Grumman Corporation', basePrice: 485, category: 'industrials' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', basePrice: 105, category: 'industrials' },
  { ticker: 'ITW', name: 'Illinois Tool Works Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'ETN', name: 'Eaton Corporation plc', basePrice: 285, category: 'industrials' },
  { ticker: 'PH', name: 'Parker-Hannifin Corporation', basePrice: 520, category: 'industrials' },
  { ticker: 'CSX', name: 'CSX Corporation', basePrice: 35, category: 'industrials' },
  { ticker: 'NSC', name: 'Norfolk Southern Corporation', basePrice: 245, category: 'industrials' },
  { ticker: 'FDX', name: 'FedEx Corporation', basePrice: 285, category: 'industrials' },
  { ticker: 'CARR', name: 'Carrier Global Corporation', basePrice: 58, category: 'industrials' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', basePrice: 105, category: 'industrials' },
  { ticker: 'JCI', name: 'Johnson Controls International', basePrice: 68, category: 'industrials' },
  { ticker: 'WM', name: 'Waste Management Inc.', basePrice: 195, category: 'industrials' },
  { ticker: 'TT', name: 'Trane Technologies plc', basePrice: 285, category: 'industrials' },
  { ticker: 'GWW', name: 'W.W. Grainger Inc.', basePrice: 885, category: 'industrials' },
  { ticker: 'CMI', name: 'Cummins Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'OTIS', name: 'Otis Worldwide Corporation', basePrice: 88, category: 'industrials' },
  { ticker: 'FAST', name: 'Fastenal Company', basePrice: 68, category: 'industrials' },
  { ticker: 'VRSK', name: 'Verisk Analytics Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'ODFL', name: 'Old Dominion Freight Line', basePrice: 385, category: 'industrials' },
  { ticker: 'IR', name: 'Ingersoll Rand Inc.', basePrice: 85, category: 'industrials' },
  { ticker: 'CPRT', name: 'Copart Inc.', basePrice: 52, category: 'industrials' },
  { ticker: 'PAYX', name: 'Paychex Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'RSG', name: 'Republic Services Inc.', basePrice: 185, category: 'industrials' },
  { ticker: 'URI', name: 'United Rentals Inc.', basePrice: 685, category: 'industrials' },
  { ticker: 'HUBB', name: 'Hubbell Incorporated', basePrice: 345, category: 'industrials' },
  { ticker: 'DOV', name: 'Dover Corporation', basePrice: 165, category: 'industrials' },
  { ticker: 'AME', name: 'AMETEK Inc.', basePrice: 165, category: 'industrials' },
  { ticker: 'ROK', name: 'Rockwell Automation Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'XYL', name: 'Xylem Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'CHRW', name: 'C.H. Robinson Worldwide Inc.', basePrice: 105, category: 'industrials' },
  { ticker: 'TDG', name: 'TransDigm Group Incorporated', basePrice: 1185, category: 'industrials' },
  { ticker: 'HWM', name: 'Howmet Aerospace Inc.', basePrice: 62, category: 'industrials' },
  { ticker: 'LHX', name: 'L3Harris Technologies Inc.', basePrice: 215, category: 'industrials' },
  { ticker: 'JBHT', name: 'J.B. Hunt Transport Services', basePrice: 185, category: 'industrials' },
  { ticker: 'EXPD', name: 'Expeditors International', basePrice: 125, category: 'industrials' },
  { ticker: 'CTAS', name: 'Cintas Corporation', basePrice: 585, category: 'industrials' },
  { ticker: 'SNA', name: 'Snap-on Incorporated', basePrice: 285, category: 'industrials' },
  { ticker: 'DAL', name: 'Delta Air Lines Inc.', basePrice: 48, category: 'industrials' },
  { ticker: 'UAL', name: 'United Airlines Holdings Inc.', basePrice: 58, category: 'industrials' },
  { ticker: 'AAL', name: 'American Airlines Group Inc.', basePrice: 14, category: 'industrials' },
  { ticker: 'LUV', name: 'Southwest Airlines Co.', basePrice: 32, category: 'industrials' },
  { ticker: 'ALK', name: 'Alaska Air Group Inc.', basePrice: 42, category: 'industrials' },
  { ticker: 'JBLU', name: 'JetBlue Airways Corporation', basePrice: 6, category: 'industrials' },
  { ticker: 'FTV', name: 'Fortive Corporation', basePrice: 78, category: 'industrials' },
  { ticker: 'TDY', name: 'Teledyne Technologies Inc.', basePrice: 445, category: 'industrials' },
  { ticker: 'LDOS', name: 'Leidos Holdings Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'PWR', name: 'Quanta Services Inc.', basePrice: 245, category: 'industrials' },
  { ticker: 'J', name: 'Jacobs Solutions Inc.', basePrice: 135, category: 'industrials' },
  { ticker: 'GPN', name: 'Global Payments Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'TXT', name: 'Textron Inc.', basePrice: 78, category: 'industrials' },
  { ticker: 'AOS', name: 'A. O. Smith Corporation', basePrice: 88, category: 'industrials' },
  { ticker: 'ALLE', name: 'Allegion plc', basePrice: 125, category: 'industrials' },
  { ticker: 'IEX', name: 'IDEX Corporation', basePrice: 215, category: 'industrials' },
  { ticker: 'PNR', name: 'Pentair plc', basePrice: 75, category: 'industrials' },
  { ticker: 'WAB', name: 'Westinghouse Air Brake Tech', basePrice: 145, category: 'industrials' },
  { ticker: 'ROL', name: 'Rollins Inc.', basePrice: 42, category: 'industrials' },
  { ticker: 'GNRC', name: 'Generac Holdings Inc.', basePrice: 135, category: 'industrials' },
  { ticker: 'AIT', name: 'Applied Industrial Technologies', basePrice: 185, category: 'industrials' },
  { ticker: 'BLDR', name: 'Builders FirstSource Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'ALSN', name: 'Allison Transmission Holdings', basePrice: 68, category: 'industrials' },
  { ticker: 'LII', name: 'Lennox International Inc.', basePrice: 485, category: 'industrials' },
  { ticker: 'AXON', name: 'Axon Enterprise Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'MIDD', name: 'The Middleby Corporation', basePrice: 145, category: 'industrials' },
  { ticker: 'VMI', name: 'Valmont Industries Inc.', basePrice: 285, category: 'industrials' },
  { ticker: 'RBC', name: 'RBC Bearings Incorporated', basePrice: 285, category: 'industrials' },
  { ticker: 'WWD', name: 'Woodward Inc.', basePrice: 145, category: 'industrials' },
  { ticker: 'OSK', name: 'Oshkosh Corporation', basePrice: 105, category: 'industrials' },
  { ticker: 'AGCO', name: 'AGCO Corporation', basePrice: 125, category: 'industrials' },
  { ticker: 'TEX', name: 'Terex Corporation', basePrice: 58, category: 'industrials' },
  { ticker: 'MLM', name: 'Martin Marietta Materials', basePrice: 485, category: 'industrials' },
  { ticker: 'VMC', name: 'Vulcan Materials Company', basePrice: 245, category: 'industrials' },
  { ticker: 'STLD', name: 'Steel Dynamics Inc.', basePrice: 125, category: 'industrials' },
  { ticker: 'NUE', name: 'Nucor Corporation', basePrice: 145, category: 'industrials' },
  { ticker: 'RS', name: 'Reliance Steel & Aluminum Co.', basePrice: 285, category: 'industrials' },
  { ticker: 'PKG', name: 'Packaging Corporation of America', basePrice: 185, category: 'industrials' },
  { ticker: 'IP', name: 'International Paper Company', basePrice: 42, category: 'industrials' },
  { ticker: 'WRK', name: 'WestRock Company', basePrice: 48, category: 'industrials' },
  { ticker: 'SEE', name: 'Sealed Air Corporation', basePrice: 38, category: 'industrials' },

  // ========== ENERGY (35 stocks) ==========
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', basePrice: 105, category: 'energy' },
  { ticker: 'CVX', name: 'Chevron Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'COP', name: 'ConocoPhillips', basePrice: 125, category: 'energy' },
  { ticker: 'SLB', name: 'Schlumberger NV', basePrice: 52, category: 'energy' },
  { ticker: 'EOG', name: 'EOG Resources Inc.', basePrice: 125, category: 'energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum Corporation', basePrice: 165, category: 'energy' },
  { ticker: 'PSX', name: 'Phillips 66', basePrice: 145, category: 'energy' },
  { ticker: 'VLO', name: 'Valero Energy Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'OXY', name: 'Occidental Petroleum Corp.', basePrice: 58, category: 'energy' },
  { ticker: 'KMI', name: 'Kinder Morgan Inc.', basePrice: 18, category: 'energy' },
  { ticker: 'WMB', name: 'The Williams Companies Inc.', basePrice: 38, category: 'energy' },
  { ticker: 'HES', name: 'Hess Corporation', basePrice: 145, category: 'energy' },
  { ticker: 'HAL', name: 'Halliburton Company', basePrice: 38, category: 'energy' },
  { ticker: 'BKR', name: 'Baker Hughes Company', basePrice: 32, category: 'energy' },
  { ticker: 'FANG', name: 'Diamondback Energy Inc.', basePrice: 185, category: 'energy' },
  { ticker: 'DVN', name: 'Devon Energy Corporation', basePrice: 48, category: 'energy' },
  { ticker: 'EQT', name: 'EQT Corporation', basePrice: 38, category: 'energy' },
  { ticker: 'TRGP', name: 'Targa Resources Corp.', basePrice: 125, category: 'energy' },
  { ticker: 'MRO', name: 'Marathon Oil Corporation', basePrice: 28, category: 'energy' },
  { ticker: 'APA', name: 'APA Corporation', basePrice: 38, category: 'energy' },
  { ticker: 'CTRA', name: 'Coterra Energy Inc.', basePrice: 28, category: 'energy' },
  { ticker: 'OKE', name: 'ONEOK Inc.', basePrice: 78, category: 'energy' },
  { ticker: 'LNG', name: 'Cheniere Energy Inc.', basePrice: 165, category: 'energy' },
  { ticker: 'VET', name: 'Vermilion Energy Inc.', basePrice: 12, category: 'energy' },
  { ticker: 'APC', name: 'Anadarko Petroleum Corporation', basePrice: 75, category: 'energy' },
  { ticker: 'NOV', name: 'NOV Inc.', basePrice: 18, category: 'energy' },
  { ticker: 'FTI', name: 'TechnipFMC plc', basePrice: 22, category: 'energy' },
  { ticker: 'CHK', name: 'Chesapeake Energy Corporation', basePrice: 88, category: 'energy' },
  { ticker: 'AR', name: 'Antero Resources Corporation', basePrice: 28, category: 'energy' },
  { ticker: 'MGY', name: 'Magnolia Oil & Gas Corporation', basePrice: 24, category: 'energy' },
  { ticker: 'PR', name: 'Permian Resources Corporation', basePrice: 14, category: 'energy' },
  { ticker: 'SM', name: 'SM Energy Company', basePrice: 42, category: 'energy' },
  { ticker: 'RRC', name: 'Range Resources Corporation', basePrice: 32, category: 'energy' },
  { ticker: 'MTDR', name: 'Matador Resources Company', basePrice: 58, category: 'energy' },
  { ticker: 'CHRD', name: 'Chord Energy Corporation', basePrice: 165, category: 'energy' },

  // ========== UTILITIES (30 stocks) ==========
  { ticker: 'NEE', name: 'NextEra Energy Inc.', basePrice: 70, category: 'utilities' },
  { ticker: 'DUK', name: 'Duke Energy Corporation', basePrice: 105, category: 'utilities' },
  { ticker: 'SO', name: 'The Southern Company', basePrice: 82, category: 'utilities' },
  { ticker: 'D', name: 'Dominion Energy Inc.', basePrice: 52, category: 'utilities' },
  { ticker: 'AEP', name: 'American Electric Power Co.', basePrice: 95, category: 'utilities' },
  { ticker: 'EXC', name: 'Exelon Corporation', basePrice: 38, category: 'utilities' },
  { ticker: 'SRE', name: 'Sempra', basePrice: 78, category: 'utilities' },
  { ticker: 'XEL', name: 'Xcel Energy Inc.', basePrice: 62, category: 'utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group Inc.', basePrice: 95, category: 'utilities' },
  { ticker: 'ED', name: 'Consolidated Edison Inc.', basePrice: 95, category: 'utilities' },
  { ticker: 'EIX', name: 'Edison International', basePrice: 75, category: 'utilities' },
  { ticker: 'AWK', name: 'American Water Works Company', basePrice: 145, category: 'utilities' },
  { ticker: 'DTE', name: 'DTE Energy Company', basePrice: 115, category: 'utilities' },
  { ticker: 'PPL', name: 'PPL Corporation', basePrice: 30, category: 'utilities' },
  { ticker: 'ES', name: 'Eversource Energy', basePrice: 62, category: 'utilities' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', basePrice: 38, category: 'utilities' },
  { ticker: 'AEE', name: 'Ameren Corporation', basePrice: 85, category: 'utilities' },
  { ticker: 'CMS', name: 'CMS Energy Corporation', basePrice: 62, category: 'utilities' },
  { ticker: 'PEG', name: 'Public Service Enterprise Group', basePrice: 68, category: 'utilities' },
  { ticker: 'ATO', name: 'Atmos Energy Corporation', basePrice: 125, category: 'utilities' },
  { ticker: 'CNP', name: 'CenterPoint Energy Inc.', basePrice: 32, category: 'utilities' },
  { ticker: 'NI', name: 'NiSource Inc.', basePrice: 30, category: 'utilities' },
  { ticker: 'LNT', name: 'Alliant Energy Corporation', basePrice: 58, category: 'utilities' },
  { ticker: 'EVRG', name: 'Evergy Inc.', basePrice: 58, category: 'utilities' },
  { ticker: 'PNW', name: 'Pinnacle West Capital Corp.', basePrice: 82, category: 'utilities' },
  { ticker: 'AES', name: 'The AES Corporation', basePrice: 18, category: 'utilities' },
  { ticker: 'VST', name: 'Vistra Corp.', basePrice: 85, category: 'utilities' },
  { ticker: 'CEG', name: 'Constellation Energy Corporation', basePrice: 185, category: 'utilities' },
  { ticker: 'PCG', name: 'PG&E Corporation', basePrice: 18, category: 'utilities' },
  { ticker: 'ETR', name: 'Entergy Corporation', basePrice: 115, category: 'utilities' },

  // ========== MEME STOCKS (10 stocks) ==========
  { ticker: 'GME', name: 'GameStop Corp.', basePrice: 20, category: 'meme' },
  { ticker: 'AMC', name: 'AMC Entertainment Holdings', basePrice: 5, category: 'meme' },
  { ticker: 'BB', name: 'BlackBerry Limited', basePrice: 4, category: 'meme' },
  { ticker: 'NOK', name: 'Nokia Corporation', basePrice: 4, category: 'meme' },
  { ticker: 'BBBY', name: 'Bed Bath & Beyond', basePrice: 1, category: 'meme' },
  { ticker: 'CLOV', name: 'Clover Health Investments', basePrice: 2, category: 'meme' },
  { ticker: 'PLUG', name: 'Plug Power Inc.', basePrice: 3, category: 'meme' },
  { ticker: 'RIVN', name: 'Rivian Automotive Inc.', basePrice: 15, category: 'meme' },
  { ticker: 'LCID', name: 'Lucid Group Inc.', basePrice: 3, category: 'meme' },
  // ========== HISTORICAL S&P 500 MEMBERS (delisted or newly added) ==========
  { ticker: 'AA', name: 'Alcoa Corporation', basePrice: 54, category: 'materials' },
  { ticker: 'ABNB', name: 'Airbnb, Inc.', basePrice: 137, category: 'consumer' },
  { ticker: 'ACGL', name: 'Arch Capital Group Ltd.', basePrice: 97, category: 'finance' },
  { ticker: 'ACT', name: 'Enact Holdings, Inc.', basePrice: 40, category: 'consumer' },
  { ticker: 'ADCT', name: 'ADC Therapeutics SA', basePrice: 4, category: 'healthcare' },
  { ticker: 'ADP', name: 'Automatic Data Processing, Inc.', basePrice: 260, category: 'tech' },
  { ticker: 'ADT', name: 'ADT Inc.', basePrice: 8, category: 'consumer' },
  { ticker: 'AET', name: 'Aetna Inc.', basePrice: 213, category: 'healthcare' },
  { ticker: 'AIV', name: 'Apartment Investment and Management Company', basePrice: 6, category: 'realestate' },
  { ticker: 'AIZ', name: 'Assurant, Inc.', basePrice: 242, category: 'finance' },
  { ticker: 'ALB', name: 'Albemarle Corporation', basePrice: 142, category: 'materials' },
  { ticker: 'AMCR', name: 'Amcor plc', basePrice: 42, category: 'materials' },
  { ticker: 'AMG', name: 'Affiliated Managers Group, Inc.', basePrice: 290, category: 'finance' },
  { ticker: 'AMT', name: 'American Tower Corporation', basePrice: 177, category: 'realestate' },
  { ticker: 'AMTM', name: 'Amentum Holdings, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', basePrice: 233, category: 'consumer' },
  { ticker: 'AN', name: 'AutoNation, Inc.', basePrice: 209, category: 'consumer' },
  { ticker: 'ANDV', name: 'Andeavor', basePrice: 154, category: 'energy' },
  { ticker: 'ANET', name: 'Arista Networks, Inc.', basePrice: 132, category: 'tech' },
  { ticker: 'ANF', name: 'Abercrombie & Fitch Co.', basePrice: 128, category: 'consumer' },
  { ticker: 'APD', name: 'Air Products and Chemicals, Inc.', basePrice: 247, category: 'materials' },
  { ticker: 'APO', name: 'Apollo Global Management, Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'APP', name: 'AppLovin Corporation', basePrice: 694, category: 'consumer' },
  { ticker: 'APTV', name: 'Aptiv PLC', basePrice: 77, category: 'consumer' },
  { ticker: 'ARE', name: 'Alexandria Real Estate Equities, Inc.', basePrice: 49, category: 'realestate' },
  { ticker: 'ARES', name: 'Ares Management Corporation', basePrice: 161, category: 'consumer' },
  { ticker: 'ATI', name: 'ATI Inc.', basePrice: 116, category: 'consumer' },
  { ticker: 'AVA', name: 'Avista Corporation', basePrice: 39, category: 'consumer' },
  { ticker: 'AVB', name: 'AvalonBay Communities, Inc.', basePrice: 183, category: 'consumer' },
  { ticker: 'AVY', name: 'Avery Dennison Corporation', basePrice: 183, category: 'materials' },
  { ticker: 'AYI', name: 'Acuity Inc.', basePrice: 365, category: 'consumer' },
  { ticker: 'BALL', name: 'Ball Corporation', basePrice: 53, category: 'materials' },
  { ticker: 'BC', name: 'Brunswick Corporation', basePrice: 75, category: 'consumer' },
  { ticker: 'BEAM', name: 'Beam Therapeutics Inc.', basePrice: 28, category: 'healthcare' },
  { ticker: 'BF-B', name: 'Brown-Forman Corporation', basePrice: 26, category: 'consumer' },
  { ticker: 'BHF', name: 'Brighthouse Financial, Inc.', basePrice: 65, category: 'finance' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.', basePrice: 5427, category: 'consumer' },
  { ticker: 'BMS', name: 'Bemis Company, Inc.', basePrice: 57, category: 'materials' },
  { ticker: 'BR', name: 'Broadridge Financial Solutions, Inc.', basePrice: 224, category: 'finance' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway Inc.', basePrice: 504, category: 'consumer' },
  { ticker: 'BTU', name: 'Peabody Energy Corporation', basePrice: 30, category: 'energy' },
  { ticker: 'BUD', name: 'Anheuser-Busch InBev SA/NV', basePrice: 65, category: 'consumer' },
  { ticker: 'BWA', name: 'BorgWarner Inc.', basePrice: 46, category: 'consumer' },
  { ticker: 'BX', name: 'Blackstone Inc.', basePrice: 153, category: 'consumer' },
  { ticker: 'BXP', name: 'BXP, Inc.', basePrice: 69, category: 'consumer' },
  { ticker: 'CA', name: 'Xtrackers California Municipal Bond ETF', basePrice: 25, category: 'tech' },
  { ticker: 'CAM', name: 'AB California Intermediate Municipal ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'CBRE', name: 'CBRE Group, Inc.', basePrice: 163, category: 'consumer' },
  { ticker: 'CCE', name: 'Coca-Cola European Partners plc', basePrice: 811, category: 'consumer' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', basePrice: 89, category: 'consumer' },
  { ticker: 'CCK', name: 'Crown Holdings, Inc.', basePrice: 103, category: 'materials' },
  { ticker: 'CDW', name: 'CDW Corporation', basePrice: 138, category: 'consumer' },
  { ticker: 'CE', name: 'Celanese Corporation', basePrice: 43, category: 'materials' },
  { ticker: 'CF', name: 'CF Industries Holdings, Inc.', basePrice: 77, category: 'materials' },
  { ticker: 'CHTR', name: 'Charter Communications, Inc.', basePrice: 210, category: 'consumer' },
  { ticker: 'CIEN', name: 'Ciena Corporation', basePrice: 238, category: 'consumer' },
  { ticker: 'CLF', name: 'Cleveland-Cliffs Inc.', basePrice: 13, category: 'materials' },
  { ticker: 'CMA', name: 'Comerica Incorporated', basePrice: 87, category: 'consumer' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', basePrice: 28, category: 'consumer' },
  { ticker: 'CNC', name: 'Centene Corporation', basePrice: 41, category: 'consumer' },
  { ticker: 'CNQ', name: 'Canadian Natural Resources Limited', basePrice: 34, category: 'consumer' },
  { ticker: 'CNX', name: 'CNX Resources Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'COHR', name: 'Coherent Corp.', basePrice: 187, category: 'consumer' },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.', basePrice: 232, category: 'consumer' },
  { ticker: 'COKE', name: 'Coca-Cola Consolidated, Inc.', basePrice: 154, category: 'consumer' },
  { ticker: 'COL', name: 'Rockwell Collins, Inc.', basePrice: 50, category: 'consumer' },
  { ticker: 'COTY', name: 'Coty Inc.', basePrice: 3, category: 'consumer' },
  { ticker: 'CPAY', name: 'Corpay, Inc.', basePrice: 305, category: 'consumer' },
  { ticker: 'CPRI', name: 'Capri Holdings Limited', basePrice: 25, category: 'consumer' },
  { ticker: 'CPT', name: 'Camden Property Trust', basePrice: 111, category: 'finance' },
  { ticker: 'CPWR', name: 'Ocean Thermal Energy Corporation', basePrice: 50, category: 'energy' },
  { ticker: 'CRH', name: 'CRH plc', basePrice: 125, category: 'consumer' },
  { ticker: 'CSGP', name: 'CoStar Group, Inc.', basePrice: 68, category: 'consumer' },
  { ticker: 'CSRA', name: 'CSRA Inc.', basePrice: 41, category: 'consumer' },
  { ticker: 'CTSH', name: 'Cognizant Technology Solutions Corporation', basePrice: 84, category: 'tech' },
  { ticker: 'CTVA', name: 'Corteva, Inc.', basePrice: 67, category: 'consumer' },
  { ticker: 'CVE', name: 'Cenovus Energy Inc.', basePrice: 17, category: 'energy' },
  { ticker: 'CVG', name: 'Convergys Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'CVNA', name: 'Carvana Co.', basePrice: 430, category: 'consumer' },
  { ticker: 'CZR', name: 'Caesars Entertainment, Inc.', basePrice: 24, category: 'consumer' },
  { ticker: 'DASH', name: 'DoorDash, Inc.', basePrice: 228, category: 'consumer' },
  { ticker: 'DAY', name: 'Dayforce, Inc.', basePrice: 69, category: 'consumer' },
  { ticker: 'DD', name: 'DuPont de Nemours, Inc.', basePrice: 41, category: 'materials' },
  { ticker: 'DECK', name: 'Deckers Outdoor Corporation', basePrice: 105, category: 'consumer' },
  { ticker: 'DHI', name: 'D.R. Horton, Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'DINO', name: 'HF Sinclair Corporation', basePrice: 46, category: 'consumer' },
  { ticker: 'DIS', name: 'The Walt Disney Company', basePrice: 115, category: 'consumer' },
  { ticker: 'DLR', name: 'Digital Realty Trust, Inc.', basePrice: 156, category: 'finance' },
  { ticker: 'DOC', name: 'Healthpeak Properties, Inc.', basePrice: 16, category: 'healthcare' },
  { ticker: 'DOW', name: 'Dow Inc.', basePrice: 24, category: 'consumer' },
  { ticker: 'DV', name: 'DoubleVerify Holdings, Inc.', basePrice: 12, category: 'consumer' },
  { ticker: 'DXC', name: 'DXC Technology Company', basePrice: 15, category: 'tech' },
  { ticker: 'DYN', name: 'Dyne Therapeutics, Inc.', basePrice: 19, category: 'healthcare' },
  { ticker: 'EA', name: 'Electronic Arts Inc.', basePrice: 204, category: 'tech' },
  { ticker: 'EBAY', name: 'eBay Inc.', basePrice: 87, category: 'consumer' },
  { ticker: 'ECL', name: 'Ecolab Inc.', basePrice: 264, category: 'consumer' },
  { ticker: 'EFX', name: 'Equifax Inc.', basePrice: 220, category: 'consumer' },
  { ticker: 'EG', name: 'Everest Group, Ltd.', basePrice: 339, category: 'consumer' },
  { ticker: 'EMC', name: 'Global X Emerging Markets Great Consumer ETF', basePrice: 31, category: 'consumer' },
  { ticker: 'EME', name: 'EMCOR Group, Inc.', basePrice: 617, category: 'consumer' },
  { ticker: 'EMN', name: 'Eastman Chemical Company', basePrice: 64, category: 'materials' },
  { ticker: 'ENB', name: 'Enbridge Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'EP', name: 'Empire Petroleum Corporation', basePrice: 3, category: 'energy' },
  { ticker: 'EQH', name: 'Equitable Holdings, Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'EQIX', name: 'Equinix, Inc.', basePrice: 770, category: 'consumer' },
  { ticker: 'EQR', name: 'Equity Residential', basePrice: 63, category: 'consumer' },
  { ticker: 'ERIE', name: 'Erie Indemnity Company', basePrice: 286, category: 'consumer' },
  { ticker: 'ESRX', name: 'Express Scripts Holding Company', basePrice: 92, category: 'consumer' },
  { ticker: 'ESS', name: 'Essex Property Trust, Inc.', basePrice: 261, category: 'finance' },
  { ticker: 'ETSY', name: 'Etsy, Inc.', basePrice: 55, category: 'consumer' },
  { ticker: 'EVHC', name: 'Envision Healthcare Corporation', basePrice: 46, category: 'healthcare' },
  { ticker: 'EXE', name: 'Expand Energy Corporation', basePrice: 111, category: 'energy' },
  { ticker: 'EXPE', name: 'Expedia Group, Inc.', basePrice: 284, category: 'consumer' },
  { ticker: 'EXR', name: 'Extra Space Storage Inc.', basePrice: 130, category: 'consumer' },
  { ticker: 'FB', name: 'ProShares S&P 500 Dynamic Daily Buffer ETF', basePrice: 42, category: 'consumer' },
  { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', basePrice: 51, category: 'consumer' },
  { ticker: 'FDS', name: 'FactSet Research Systems Inc.', basePrice: 290, category: 'tech' },
  { ticker: 'FHN', name: 'First Horizon Corporation', basePrice: 24, category: 'consumer' },
  { ticker: 'FICO', name: 'Fair Isaac Corporation', basePrice: 1746, category: 'consumer' },
  { ticker: 'FIX', name: 'Comfort Systems USA, Inc.', basePrice: 946, category: 'tech' },
  { ticker: 'FLO', name: 'Flowers Foods, Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'FLR', name: 'Fluor Corporation', basePrice: 40, category: 'consumer' },
  { ticker: 'FLS', name: 'Flowserve Corporation', basePrice: 70, category: 'consumer' },
  { ticker: 'FMC', name: 'FMC Corporation', basePrice: 14, category: 'materials' },
  { ticker: 'FNF', name: 'Fidelity National Financial, Inc.', basePrice: 55, category: 'finance' },
  { ticker: 'FOSL', name: 'Fossil Group, Inc.', basePrice: 4, category: 'consumer' },
  { ticker: 'FOX', name: 'Fox Corporation', basePrice: 65, category: 'consumer' },
  { ticker: 'FOXA', name: 'Fox Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'FRT', name: 'Federal Realty Investment Trust', basePrice: 101, category: 'finance' },
  { ticker: 'GEHC', name: 'GE HealthCare Technologies Inc.', basePrice: 83, category: 'healthcare' },
  { ticker: 'GEV', name: 'GE Vernova Inc.', basePrice: 659, category: 'consumer' },
  { ticker: 'GHC', name: 'Graham Holdings Company', basePrice: 1091, category: 'consumer' },
  { ticker: 'GNW', name: 'Genworth Financial, Inc.', basePrice: 9, category: 'finance' },
  { ticker: 'GR', name: 'Goodrich Corporation', basePrice: 50, category: 'industrials' },
  { ticker: 'GRMN', name: 'Garmin Ltd.', basePrice: 204, category: 'consumer' },
  { ticker: 'GRN', name: 'iPath Series B Carbon ETN', basePrice: 34, category: 'consumer' },
  { ticker: 'GT', name: 'The Goodyear Tire & Rubber Company', basePrice: 9, category: 'consumer' },
  { ticker: 'HAR', name: 'Harman International Industries', basePrice: 10150, category: 'tech' },
  { ticker: 'HD', name: 'The Home Depot, Inc.', basePrice: 346, category: 'consumer' },
  { ticker: 'HII', name: 'Huntington Ingalls Industries, Inc.', basePrice: 341, category: 'consumer' },
  { ticker: 'HLF', name: 'Herbalife Ltd.', basePrice: 13, category: 'consumer' },
  { ticker: 'HOG', name: 'Harley-Davidson, Inc.', basePrice: 21, category: 'consumer' },
  { ticker: 'HOOD', name: 'Robinhood Markets, Inc.', basePrice: 115, category: 'consumer' },
  { ticker: 'HOT', name: 'Starwood Hotels & Resorts Worldwide', basePrice: 77, category: 'consumer' },
  { ticker: 'HP', name: 'Helmerich & Payne, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'HRB', name: 'H&R Block, Inc.', basePrice: 43, category: 'consumer' },
  { ticker: 'HST', name: 'Host Hotels & Resorts, Inc.', basePrice: 18, category: 'consumer' },
  { ticker: 'HUN', name: 'Huntsman Corporation', basePrice: 10, category: 'materials' },
  { ticker: 'IBKR', name: 'Interactive Brokers Group, Inc.', basePrice: 65, category: 'consumer' },
  { ticker: 'IFF', name: 'International Flavors & Fragrances Inc.', basePrice: 68, category: 'materials' },
  { ticker: 'IMO', name: 'Imperial Oil Limited', basePrice: 87, category: 'energy' },
  { ticker: 'INFO', name: 'Harbor PanAgora Dynamic Large Cap Core ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'INGR', name: 'Ingredion Incorporated', basePrice: 110, category: 'consumer' },
  { ticker: 'INVH', name: 'Invitation Homes Inc.', basePrice: 28, category: 'consumer' },
  { ticker: 'IPGP', name: 'IPG Photonics Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'IRM', name: 'Iron Mountain Incorporated', basePrice: 83, category: 'consumer' },
  { ticker: 'IT', name: 'Gartner, Inc.', basePrice: 255, category: 'consumer' },
  { ticker: 'ITT', name: 'ITT Inc.', basePrice: 176, category: 'consumer' },
  { ticker: 'JBL', name: 'Jabil Inc.', basePrice: 232, category: 'consumer' },
  { ticker: 'JEF', name: 'Jefferies Financial Group Inc.', basePrice: 62, category: 'finance' },
  { ticker: 'JKHY', name: 'Jack Henry & Associates, Inc.', basePrice: 185, category: 'consumer' },
  { ticker: 'Jazz', name: 'Jazz Pharmaceuticals plc', basePrice: 171, category: 'healthcare' },
  { ticker: 'KBH', name: 'KB Home', basePrice: 57, category: 'consumer' },
  { ticker: 'KG', name: 'Kestrel Group Ltd', basePrice: 10, category: 'consumer' },
  { ticker: 'KIM', name: 'Kimco Realty Corporation', basePrice: 20, category: 'realestate' },
  { ticker: 'KKR', name: 'KKR & Co. Inc.', basePrice: 128, category: 'consumer' },
  { ticker: 'KMX', name: 'CarMax, Inc.', basePrice: 39, category: 'consumer' },
  { ticker: 'KSS', name: 'Kohl\'s Corporation', basePrice: 20, category: 'consumer' },
  { ticker: 'LEG', name: 'Leggett & Platt, Incorporated', basePrice: 11, category: 'consumer' },
  { ticker: 'LEN', name: 'Lennar Corporation', basePrice: 103, category: 'consumer' },
  { ticker: 'LIN', name: 'Linde plc', basePrice: 428, category: 'consumer' },
  { ticker: 'LITE', name: 'Lumentum Holdings Inc.', basePrice: 371, category: 'consumer' },
  { ticker: 'LKQ', name: 'LKQ Corporation', basePrice: 31, category: 'consumer' },
  { ticker: 'LNC', name: 'Lincoln National Corporation', basePrice: 44, category: 'consumer' },
  { ticker: 'LOW', name: 'Lowe\'s Companies, Inc.', basePrice: 242, category: 'consumer' },
  { ticker: 'LULU', name: 'lululemon athletica inc.', basePrice: 211, category: 'consumer' },
  { ticker: 'LUMN', name: 'Lumen Technologies, Inc.', basePrice: 8, category: 'tech' },
  { ticker: 'LW', name: 'Lamb Weston Holdings, Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'LYB', name: 'LyondellBasell Industries N.V.', basePrice: 44, category: 'materials' },
  { ticker: 'LYV', name: 'Live Nation Entertainment, Inc.', basePrice: 144, category: 'consumer' },
  { ticker: 'M', name: 'Macy\'s, Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'MAA', name: 'Mid-America Apartment Communities, Inc.', basePrice: 138, category: 'realestate' },
  { ticker: 'MAC', name: 'The Macerich Company', basePrice: 18, category: 'consumer' },
  { ticker: 'MAS', name: 'Masco Corporation', basePrice: 64, category: 'consumer' },
  { ticker: 'MBC', name: 'MasterBrand, Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'MBI', name: 'MBIA Inc.', basePrice: 7, category: 'consumer' },
  { ticker: 'MHK', name: 'Mohawk Industries, Inc.', basePrice: 110, category: 'consumer' },
  { ticker: 'MHS', name: 'Morningstar US Healthcare', basePrice: 15893, category: 'healthcare' },
  { ticker: 'MI', name: 'NFT Limited', basePrice: 4, category: 'consumer' },
  { ticker: 'MKC', name: 'McCormick & Company, Incorporated', basePrice: 68, category: 'consumer' },
  { ticker: 'MKTX', name: 'MarketAxess Holdings Inc.', basePrice: 182, category: 'consumer' },
  { ticker: 'MMI', name: 'Marcus & Millichap, Inc.', basePrice: 27, category: 'consumer' },
  { ticker: 'MOS', name: 'The Mosaic Company', basePrice: 24, category: 'materials' },
  { ticker: 'MRSH', name: 'Marsh & McLennan Companies, Inc.', basePrice: 186, category: 'consumer' },
  { ticker: 'MSI', name: 'Motorola Solutions, Inc.', basePrice: 383, category: 'consumer' },
  { ticker: 'MTCH', name: 'Match Group, Inc.', basePrice: 32, category: 'consumer' },
  { ticker: 'MUR', name: 'Murphy Oil Corporation', basePrice: 31, category: 'energy' },
  { ticker: 'NAVI', name: 'Navient Corporation', basePrice: 13, category: 'consumer' },
  { ticker: 'NBR', name: 'Nabors Industries Ltd.', basePrice: 55, category: 'consumer' },
  { ticker: 'NCC', name: 'National City Corporation', basePrice: 2, category: 'finance' },
  { ticker: 'NDSN', name: 'Nordson Corporation', basePrice: 243, category: 'consumer' },
  { ticker: 'NE', name: 'Noble Corporation plc', basePrice: 28, category: 'consumer' },
  { ticker: 'NEM', name: 'Newmont Corporation', basePrice: 102, category: 'consumer' },
  { ticker: 'NFLX', name: 'Netflix, Inc.', basePrice: 94, category: 'consumer' },
  { ticker: 'NFX', name: 'Newfield Exploration Company', basePrice: 17, category: 'consumer' },
  { ticker: 'NKTR', name: 'Nektar Therapeutics', basePrice: 42, category: 'healthcare' },
  { ticker: 'NRG', name: 'NRG Energy, Inc.', basePrice: 160, category: 'energy' },
  { ticker: 'NSM', name: 'Nationstar Mortgage Holdings Inc.', basePrice: 18, category: 'finance' },
  { ticker: 'NTR', name: 'Nutrien Ltd.', basePrice: 62, category: 'materials' },
  { ticker: 'NVR', name: 'NVR, Inc.', basePrice: 7327, category: 'consumer' },
  { ticker: 'NWE', name: 'NorthWestern Energy Group, Inc.', basePrice: 65, category: 'energy' },
  { ticker: 'NWS', name: 'News Corporation', basePrice: 30, category: 'consumer' },
  { ticker: 'NWSA', name: 'News Corporation', basePrice: 26, category: 'consumer' },
  { ticker: 'NYT', name: 'The New York Times Company', basePrice: 70, category: 'consumer' },
  { ticker: 'O', name: 'Realty Income Corporation', basePrice: 57, category: 'realestate' },
  { ticker: 'OGE', name: 'OGE Energy Corp.', basePrice: 43, category: 'energy' },
  { ticker: 'OGN', name: 'Organon & Co.', basePrice: 7, category: 'consumer' },
  { ticker: 'OI', name: 'O-I Glass, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'OMC', name: 'Omnicom Group Inc.', basePrice: 80, category: 'consumer' },
  { ticker: 'PAYC', name: 'Paycom Software, Inc.', basePrice: 160, category: 'tech' },
  { ticker: 'PBI', name: 'Pitney Bowes Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'PCL', name: 'PGIM Corporate Bond 10+ Year ETF', basePrice: 50, category: 'consumer' },
  { ticker: 'PCLN', name: 'Pictet Cleaner Planet ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'PCS', name: 'PGIM Corporate Bond 0-5 Year ETF', basePrice: 50, category: 'consumer' },
  { ticker: 'PENN', name: 'PENN Entertainment, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'PHM', name: 'PulteGroup, Inc.', basePrice: 118, category: 'consumer' },
  { ticker: 'PLD', name: 'Prologis, Inc.', basePrice: 129, category: 'consumer' },
  { ticker: 'POM', name: 'Pomdoctor Limited', basePrice: 50, category: 'consumer' },
  { ticker: 'POOL', name: 'Pool Corporation', basePrice: 231, category: 'consumer' },
  { ticker: 'POST', name: 'Post Holdings, Inc.', basePrice: 99, category: 'consumer' },
  { ticker: 'PPG', name: 'PPG Industries, Inc.', basePrice: 104, category: 'consumer' },
  { ticker: 'PRGO', name: 'Perrigo Company plc', basePrice: 14, category: 'consumer' },
  { ticker: 'PSA', name: 'Public Storage', basePrice: 261, category: 'consumer' },
  { ticker: 'PSKY', name: 'Paramount Skydance Corporation', basePrice: 13, category: 'consumer' },
  { ticker: 'PTC', name: 'PTC Inc.', basePrice: 175, category: 'consumer' },
  { ticker: 'Q', name: 'Qnity Electronics, Inc.', basePrice: 84, category: 'tech' },
  { ticker: 'R', name: 'Ryder System, Inc.', basePrice: 192, category: 'consumer' },
  { ticker: 'REG', name: 'Regency Centers Corporation', basePrice: 70, category: 'consumer' },
  { ticker: 'RHI', name: 'Robert Half Inc.', basePrice: 27, category: 'consumer' },
  { ticker: 'RIG', name: 'Transocean Ltd.', basePrice: 4, category: 'consumer' },
  { ticker: 'RSH', name: 'RadioShack Corporation', basePrice: 53, category: 'consumer' },
  { ticker: 'RVTY', name: 'Revvity, Inc.', basePrice: 97, category: 'consumer' },
  { ticker: 'S', name: 'SentinelOne, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'SATS', name: 'EchoStar Corporation', basePrice: 109, category: 'consumer' },
  { ticker: 'SBAC', name: 'SBA Communications Corporation', basePrice: 195, category: 'consumer' },
  { ticker: 'SBNY', name: 'Signature Bank', basePrice: 1, category: 'finance' },
  { ticker: 'SCG', name: 'SCANA Corporation', basePrice: 48, category: 'consumer' },
  { ticker: 'SE', name: 'Sea Limited', basePrice: 128, category: 'consumer' },
  { ticker: 'SEDG', name: 'SolarEdge Technologies, Inc.', basePrice: 29, category: 'tech' },
  { ticker: 'SHLD', name: 'Global X Defense Tech ETF', basePrice: 65, category: 'tech' },
  { ticker: 'SHW', name: 'The Sherwin-Williams Company', basePrice: 326, category: 'consumer' },
  { ticker: 'SIG', name: 'Signet Jewelers Limited', basePrice: 83, category: 'consumer' },
  { ticker: 'SII', name: 'Sprott Inc.', basePrice: 98, category: 'consumer' },
  { ticker: 'SLE', name: 'Super League Enterprise, Inc.', basePrice: 7, category: 'consumer' },
  { ticker: 'SLG', name: 'SL Green Realty Corp.', basePrice: 46, category: 'realestate' },
  { ticker: 'SLM', name: 'SLM Corporation', basePrice: 27, category: 'consumer' },
  { ticker: 'SNDK', name: 'Sandisk Corporation', basePrice: 240, category: 'consumer' },
  { ticker: 'SOLS', name: 'Solstice Advanced Materials, Inc.', basePrice: 49, category: 'consumer' },
  { ticker: 'SOLV', name: 'Solventum Corporation', basePrice: 80, category: 'consumer' },
  { ticker: 'SPB', name: 'Spectrum Brands Holdings, Inc.', basePrice: 59, category: 'consumer' },
  { ticker: 'SPG', name: 'Simon Property Group, Inc.', basePrice: 187, category: 'consumer' },
  { ticker: 'STI', name: 'Solidion Technology, Inc.', basePrice: 8, category: 'finance' },
  { ticker: 'SU', name: 'Suncor Energy Inc.', basePrice: 44, category: 'energy' },
  { ticker: 'SUN', name: 'Sunoco LP', basePrice: 52, category: 'consumer' },
  { ticker: 'SVU', name: 'SUPERVALU INC.', basePrice: 32, category: 'consumer' },
  { ticker: 'SW', name: 'Smurfit Westrock Plc', basePrice: 38, category: 'consumer' },
  { ticker: 'SWK', name: 'Stanley Black & Decker, Inc.', basePrice: 75, category: 'consumer' },
  { ticker: 'T', name: 'AT&T Inc.', basePrice: 25, category: 'consumer' },
  { ticker: 'TDC', name: 'Teradata Corporation', basePrice: 31, category: 'tech' },
  { ticker: 'TE', name: 'T1 Energy Inc.', basePrice: 6, category: 'energy' },
  { ticker: 'TEG', name: 'TEG', basePrice: 15100, category: 'consumer' },
  { ticker: 'TEL', name: 'TE Connectivity plc', basePrice: 230, category: 'consumer' },
  { ticker: 'TGNA', name: 'TEGNA Inc.', basePrice: 19, category: 'consumer' },
  { ticker: 'THC', name: 'Tenet Healthcare Corporation', basePrice: 201, category: 'healthcare' },
  { ticker: 'TKO', name: 'TKO Group Holdings, Inc.', basePrice: 213, category: 'consumer' },
  { ticker: 'TLAB', name: 'Tellabs Inc.', basePrice: 2, category: 'tech' },
  { ticker: 'TMC', name: 'TMC the metals company Inc.', basePrice: 6, category: 'materials' },
  { ticker: 'TMUS', name: 'T-Mobile US, Inc.', basePrice: 204, category: 'consumer' },
  { ticker: 'TPL', name: 'Texas Pacific Land Corporation', basePrice: 293, category: 'consumer' },
  { ticker: 'TRIP', name: 'Tripadvisor, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'TRMB', name: 'Trimble Inc.', basePrice: 80, category: 'consumer' },
  { ticker: 'TRP', name: 'TC Energy Corporation', basePrice: 56, category: 'energy' },
  { ticker: 'TSCO', name: 'Tractor Supply Company', basePrice: 50, category: 'consumer' },
  { ticker: 'TTD', name: 'The Trade Desk, Inc.', basePrice: 38, category: 'consumer' },
  { ticker: 'TTWO', name: 'Take-Two Interactive Software, Inc.', basePrice: 258, category: 'tech' },
  { ticker: 'TWX', name: 'Time Warner Inc.', basePrice: 99, category: 'consumer' },
  { ticker: 'UA', name: 'Under Armour, Inc.', basePrice: 5, category: 'consumer' },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.', basePrice: 82, category: 'tech' },
  { ticker: 'UDR', name: 'UDR, Inc.', basePrice: 37, category: 'consumer' },
  { ticker: 'UNM', name: 'Unum Group', basePrice: 78, category: 'consumer' },
  { ticker: 'URBN', name: 'Urban Outfitters, Inc.', basePrice: 75, category: 'consumer' },
  { ticker: 'USL', name: 'United States 12 Month Oil Fund, LP', basePrice: 34, category: 'finance' },
  { ticker: 'VICI', name: 'VICI Properties Inc.', basePrice: 28, category: 'realestate' },
  { ticker: 'VLTO', name: 'Veralto Corporation', basePrice: 101, category: 'consumer' },
  { ticker: 'VNO', name: 'Vornado Realty Trust', basePrice: 34, category: 'finance' },
  { ticker: 'VNT', name: 'Vontier Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'VRT', name: 'Vertiv Holdings Co', basePrice: 164, category: 'consumer' },
  { ticker: 'VTR', name: 'Ventas, Inc.', basePrice: 78, category: 'consumer' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', basePrice: 40, category: 'consumer' },
  { ticker: 'WB', name: 'Weibo Corporation', basePrice: 10, category: 'finance' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'WELL', name: 'Welltower Inc.', basePrice: 188, category: 'consumer' },
  { ticker: 'WSM', name: 'Williams-Sonoma, Inc.', basePrice: 181, category: 'consumer' },
  { ticker: 'WST', name: 'West Pharmaceutical Services, Inc.', basePrice: 277, category: 'healthcare' },
  { ticker: 'WU', name: 'The Western Union Company', basePrice: 9, category: 'consumer' },
  { ticker: 'WY', name: 'Weyerhaeuser Company', basePrice: 24, category: 'consumer' },
  { ticker: 'XRX', name: 'Xerox Holdings Corporation', basePrice: 2, category: 'consumer' },
  { ticker: 'XYZ', name: 'Block, Inc.', basePrice: 66, category: 'consumer' },
  { ticker: 'ZBH', name: 'Zimmer Biomet Holdings, Inc.', basePrice: 91, category: 'healthcare' },
  { ticker: 'ZION', name: 'Zions Bancorporation, National Association', basePrice: 59, category: 'consumer' },
];
