  { ticker: 'ABNB', name: 'Airbnb, Inc.', basePrice: 137, category: 'consumer' },
  { ticker: 'ACT', name: 'Enact Holdings, Inc.', basePrice: 40, category: 'consumer' },
  { ticker: 'ADT', name: 'ADT Inc.', basePrice: 8, category: 'consumer' },
  { ticker: 'AMTM', name: 'Amentum Holdings, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', basePrice: 233, category: 'consumer' },
  { ticker: 'AN', name: 'AutoNation, Inc.', basePrice: 209, category: 'consumer' },
  { ticker: 'ANF', name: 'Abercrombie & Fitch Co.', basePrice: 128, category: 'consumer' },
  { ticker: 'APO', name: 'Apollo Global Management, Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'APP', name: 'AppLovin Corporation', basePrice: 694, category: 'consumer' },
  { ticker: 'APTV', name: 'Aptiv PLC', basePrice: 77, category: 'consumer' },
  { ticker: 'ARES', name: 'Ares Management Corporation', basePrice: 161, category: 'consumer' },
  { ticker: 'ATI', name: 'ATI Inc.', basePrice: 116, category: 'consumer' },
  { ticker: 'AVA', name: 'Avista Corporation', basePrice: 39, category: 'consumer' },
  { ticker: 'AVB', name: 'AvalonBay Communities, Inc.', basePrice: 183, category: 'consumer' },
  { ticker: 'AYI', name: 'Acuity Inc.', basePrice: 365, category: 'consumer' },
  { ticker: 'BC', name: 'Brunswick Corporation', basePrice: 75, category: 'consumer' },
  { ticker: 'BF-B', name: 'Brown-Forman Corporation', basePrice: 26, category: 'consumer' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.', basePrice: 5427, category: 'consumer' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway Inc.', basePrice: 504, category: 'consumer' },
  { ticker: 'BUD', name: 'Anheuser-Busch InBev SA/NV', basePrice: 65, category: 'consumer' },
  { ticker: 'BWA', name: 'BorgWarner Inc.', basePrice: 46, category: 'consumer' },
  { ticker: 'BX', name: 'Blackstone Inc.', basePrice: 153, category: 'consumer' },
  { ticker: 'BXP', name: 'BXP, Inc.', basePrice: 69, category: 'consumer' },
  { ticker: 'CAM', name: 'AB California Intermediate Municipal ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'CBRE', name: 'CBRE Group, Inc.', basePrice: 163, category: 'consumer' },
  { ticker: 'CCE', name: 'Coca-Cola European Partners plc', basePrice: 811, category: 'consumer' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', basePrice: 89, category: 'consumer' },
  { ticker: 'CDW', name: 'CDW Corporation', basePrice: 138, category: 'consumer' },
  { ticker: 'CHTR', name: 'Charter Communications, Inc.', basePrice: 210, category: 'consumer' },
  { ticker: 'CIEN', name: 'Ciena Corporation', basePrice: 238, category: 'consumer' },
  { ticker: 'CMA', name: 'Comerica Incorporated', basePrice: 87, category: 'consumer' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', basePrice: 28, category: 'consumer' },
  { ticker: 'CNC', name: 'Centene Corporation', basePrice: 41, category: 'consumer' },
  { ticker: 'CNQ', name: 'Canadian Natural Resources Limited', basePrice: 34, category: 'consumer' },
  { ticker: 'CNX', name: 'CNX Resources Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'COHR', name: 'Coherent Corp.', basePrice: 187, category: 'consumer' },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.', basePrice: 232, category: 'consumer' },
  { ticker: 'COKE', name: 'Coca-Cola Consolidated, Inc.', basePrice: 154, category: 'consumer' },
  { ticker: 'COL', name: 'Rockwell Collins, Inc.', basePrice: 50, category: 'consumer' },
  { ticker: 'COTY', name: 'Coty Inc.', basePrice: 3, category: 'consumer' },
  { ticker: 'CPAY', name: 'Corpay, Inc.', basePrice: 305, category: 'consumer' },
  { ticker: 'CPRI', name: 'Capri Holdings Limited', basePrice: 25, category: 'consumer' },
  { ticker: 'CRH', name: 'CRH plc', basePrice: 125, category: 'consumer' },
  { ticker: 'CSGP', name: 'CoStar Group, Inc.', basePrice: 68, category: 'consumer' },
  { ticker: 'CSRA', name: 'CSRA Inc.', basePrice: 41, category: 'consumer' },
  { ticker: 'CTVA', name: 'Corteva, Inc.', basePrice: 67, category: 'consumer' },
  { ticker: 'CVG', name: 'Convergys Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'CVNA', name: 'Carvana Co.', basePrice: 430, category: 'consumer' },
  { ticker: 'CZR', name: 'Caesars Entertainment, Inc.', basePrice: 24, category: 'consumer' },
  { ticker: 'DASH', name: 'DoorDash, Inc.', basePrice: 228, category: 'consumer' },
  { ticker: 'DAY', name: 'Dayforce, Inc.', basePrice: 69, category: 'consumer' },
  { ticker: 'DECK', name: 'Deckers Outdoor Corporation', basePrice: 105, category: 'consumer' },
  { ticker: 'DHI', name: 'D.R. Horton, Inc.', basePrice: 145, category: 'consumer' },
  { ticker: 'DINO', name: 'HF Sinclair Corporation', basePrice: 46, category: 'consumer' },
  { ticker: 'DIS', name: 'The Walt Disney Company', basePrice: 115, category: 'consumer' },
  { ticker: 'DOW', name: 'Dow Inc.', basePrice: 24, category: 'consumer' },
  { ticker: 'DV', name: 'DoubleVerify Holdings, Inc.', basePrice: 12, category: 'consumer' },
  { ticker: 'EBAY', name: 'eBay Inc.', basePrice: 87, category: 'consumer' },
  { ticker: 'ECL', name: 'Ecolab Inc.', basePrice: 264, category: 'consumer' },
  { ticker: 'EFX', name: 'Equifax Inc.', basePrice: 220, category: 'consumer' },
  { ticker: 'EG', name: 'Everest Group, Ltd.', basePrice: 339, category: 'consumer' },
  { ticker: 'EMC', name: 'Global X Emerging Markets Great Consumer ETF', basePrice: 31, category: 'consumer' },
  { ticker: 'EME', name: 'EMCOR Group, Inc.', basePrice: 617, category: 'consumer' },
  { ticker: 'ENB', name: 'Enbridge Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'EQH', name: 'Equitable Holdings, Inc.', basePrice: 48, category: 'consumer' },
  { ticker: 'EQIX', name: 'Equinix, Inc.', basePrice: 770, category: 'consumer' },
  { ticker: 'EQR', name: 'Equity Residential', basePrice: 63, category: 'consumer' },
  { ticker: 'ERIE', name: 'Erie Indemnity Company', basePrice: 286, category: 'consumer' },
  { ticker: 'ESRX', name: 'Express Scripts Holding Company', basePrice: 92, category: 'consumer' },
  { ticker: 'ETSY', name: 'Etsy, Inc.', basePrice: 55, category: 'consumer' },
  { ticker: 'EXPE', name: 'Expedia Group, Inc.', basePrice: 284, category: 'consumer' },
  { ticker: 'EXR', name: 'Extra Space Storage Inc.', basePrice: 130, category: 'consumer' },
  { ticker: 'FB', name: 'ProShares S&P 500 Dynamic Daily Buffer ETF', basePrice: 42, category: 'consumer' },
  { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', basePrice: 51, category: 'consumer' },
  { ticker: 'FHN', name: 'First Horizon Corporation', basePrice: 24, category: 'consumer' },
  { ticker: 'FICO', name: 'Fair Isaac Corporation', basePrice: 1746, category: 'consumer' },
  { ticker: 'FLO', name: 'Flowers Foods, Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'FLR', name: 'Fluor Corporation', basePrice: 40, category: 'consumer' },
  { ticker: 'FLS', name: 'Flowserve Corporation', basePrice: 70, category: 'consumer' },
  { ticker: 'FOSL', name: 'Fossil Group, Inc.', basePrice: 4, category: 'consumer' },
  { ticker: 'FOX', name: 'Fox Corporation', basePrice: 65, category: 'consumer' },
  { ticker: 'FOXA', name: 'Fox Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'GEV', name: 'GE Vernova Inc.', basePrice: 659, category: 'consumer' },
  { ticker: 'GHC', name: 'Graham Holdings Company', basePrice: 1091, category: 'consumer' },
  { ticker: 'GRMN', name: 'Garmin Ltd.', basePrice: 204, category: 'consumer' },
  { ticker: 'GRN', name: 'iPath Series B Carbon ETN', basePrice: 34, category: 'consumer' },
  { ticker: 'GT', name: 'The Goodyear Tire & Rubber Company', basePrice: 9, category: 'consumer' },
  { ticker: 'HD', name: 'The Home Depot, Inc.', basePrice: 346, category: 'consumer' },
  { ticker: 'HII', name: 'Huntington Ingalls Industries, Inc.', basePrice: 341, category: 'consumer' },
  { ticker: 'HLF', name: 'Herbalife Ltd.', basePrice: 13, category: 'consumer' },
  { ticker: 'HOG', name: 'Harley-Davidson, Inc.', basePrice: 21, category: 'consumer' },
  { ticker: 'HOOD', name: 'Robinhood Markets, Inc.', basePrice: 115, category: 'consumer' },
  { ticker: 'HP', name: 'Helmerich & Payne, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'HRB', name: 'H&R Block, Inc.', basePrice: 43, category: 'consumer' },
  { ticker: 'HST', name: 'Host Hotels & Resorts, Inc.', basePrice: 18, category: 'consumer' },
  { ticker: 'IBKR', name: 'Interactive Brokers Group, Inc.', basePrice: 65, category: 'consumer' },
  { ticker: 'INFO', name: 'Harbor PanAgora Dynamic Large Cap Core ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'INGR', name: 'Ingredion Incorporated', basePrice: 110, category: 'consumer' },
  { ticker: 'INVH', name: 'Invitation Homes Inc.', basePrice: 28, category: 'consumer' },
  { ticker: 'IPGP', name: 'IPG Photonics Corporation', basePrice: 73, category: 'consumer' },
  { ticker: 'IRM', name: 'Iron Mountain Incorporated', basePrice: 83, category: 'consumer' },
  { ticker: 'IT', name: 'Gartner, Inc.', basePrice: 255, category: 'consumer' },
  { ticker: 'ITT', name: 'ITT Inc.', basePrice: 176, category: 'consumer' },
  { ticker: 'JBL', name: 'Jabil Inc.', basePrice: 232, category: 'consumer' },
  { ticker: 'JKHY', name: 'Jack Henry & Associates, Inc.', basePrice: 185, category: 'consumer' },
  { ticker: 'KBH', name: 'KB Home', basePrice: 57, category: 'consumer' },
  { ticker: 'KG', name: 'Kestrel Group Ltd', basePrice: 10, category: 'consumer' },
  { ticker: 'KKR', name: 'KKR & Co. Inc.', basePrice: 128, category: 'consumer' },
  { ticker: 'KMX', name: 'CarMax, Inc.', basePrice: 39, category: 'consumer' },
  { ticker: 'KSS', name: 'Kohl\'s Corporation', basePrice: 20, category: 'consumer' },
  { ticker: 'LEG', name: 'Leggett & Platt, Incorporated', basePrice: 11, category: 'consumer' },
  { ticker: 'LEN', name: 'Lennar Corporation', basePrice: 103, category: 'consumer' },
  { ticker: 'LIN', name: 'Linde plc', basePrice: 428, category: 'consumer' },
  { ticker: 'LITE', name: 'Lumentum Holdings Inc.', basePrice: 371, category: 'consumer' },
  { ticker: 'LKQ', name: 'LKQ Corporation', basePrice: 31, category: 'consumer' },
  { ticker: 'LNC', name: 'Lincoln National Corporation', basePrice: 44, category: 'consumer' },
  { ticker: 'LOW', name: 'Lowe\'s Companies, Inc.', basePrice: 242, category: 'consumer' },
  { ticker: 'LULU', name: 'lululemon athletica inc.', basePrice: 211, category: 'consumer' },
  { ticker: 'LW', name: 'Lamb Weston Holdings, Inc.', basePrice: 42, category: 'consumer' },
  { ticker: 'LYV', name: 'Live Nation Entertainment, Inc.', basePrice: 144, category: 'consumer' },
  { ticker: 'M', name: 'Macy\'s, Inc.', basePrice: 22, category: 'consumer' },
  { ticker: 'MAC', name: 'The Macerich Company', basePrice: 18, category: 'consumer' },
  { ticker: 'MAS', name: 'Masco Corporation', basePrice: 64, category: 'consumer' },
  { ticker: 'MBC', name: 'MasterBrand, Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'MBI', name: 'MBIA Inc.', basePrice: 7, category: 'consumer' },
  { ticker: 'MHK', name: 'Mohawk Industries, Inc.', basePrice: 110, category: 'consumer' },
  { ticker: 'MI', name: 'NFT Limited', basePrice: 4, category: 'consumer' },
  { ticker: 'MKC', name: 'McCormick & Company, Incorporated', basePrice: 68, category: 'consumer' },
  { ticker: 'MKTX', name: 'MarketAxess Holdings Inc.', basePrice: 182, category: 'consumer' },
  { ticker: 'MMI', name: 'Marcus & Millichap, Inc.', basePrice: 27, category: 'consumer' },
  { ticker: 'MRSH', name: 'Marsh & McLennan Companies, Inc.', basePrice: 186, category: 'consumer' },
  { ticker: 'MSI', name: 'Motorola Solutions, Inc.', basePrice: 383, category: 'consumer' },
  { ticker: 'MTCH', name: 'Match Group, Inc.', basePrice: 32, category: 'consumer' },
  { ticker: 'NAVI', name: 'Navient Corporation', basePrice: 13, category: 'consumer' },
  { ticker: 'NBR', name: 'Nabors Industries Ltd.', basePrice: 55, category: 'consumer' },
  { ticker: 'NDSN', name: 'Nordson Corporation', basePrice: 243, category: 'consumer' },
  { ticker: 'NE', name: 'Noble Corporation plc', basePrice: 28, category: 'consumer' },
  { ticker: 'NEM', name: 'Newmont Corporation', basePrice: 102, category: 'consumer' },
  { ticker: 'NFLX', name: 'Netflix, Inc.', basePrice: 94, category: 'consumer' },
  { ticker: 'NFX', name: 'Newfield Exploration Company', basePrice: 17, category: 'consumer' },
  { ticker: 'NVR', name: 'NVR, Inc.', basePrice: 7327, category: 'consumer' },
  { ticker: 'NWS', name: 'News Corporation', basePrice: 30, category: 'consumer' },
  { ticker: 'NWSA', name: 'News Corporation', basePrice: 26, category: 'consumer' },
  { ticker: 'NYT', name: 'The New York Times Company', basePrice: 70, category: 'consumer' },
  { ticker: 'OGN', name: 'Organon & Co.', basePrice: 7, category: 'consumer' },
  { ticker: 'OMC', name: 'Omnicom Group Inc.', basePrice: 80, category: 'consumer' },
  { ticker: 'PBI', name: 'Pitney Bowes Inc.', basePrice: 11, category: 'consumer' },
  { ticker: 'PCL', name: 'PGIM Corporate Bond 10+ Year ETF', basePrice: 50, category: 'consumer' },
  { ticker: 'PCLN', name: 'Pictet Cleaner Planet ETF', basePrice: 25, category: 'consumer' },
  { ticker: 'PCS', name: 'PGIM Corporate Bond 0-5 Year ETF', basePrice: 50, category: 'consumer' },
  { ticker: 'PENN', name: 'PENN Entertainment, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'PHM', name: 'PulteGroup, Inc.', basePrice: 118, category: 'consumer' },
  { ticker: 'PLD', name: 'Prologis, Inc.', basePrice: 129, category: 'consumer' },
  { ticker: 'POM', name: 'Pomdoctor Limited', basePrice: 50, category: 'consumer' },
  { ticker: 'POOL', name: 'Pool Corporation', basePrice: 231, category: 'consumer' },
  { ticker: 'POST', name: 'Post Holdings, Inc.', basePrice: 99, category: 'consumer' },
  { ticker: 'PPG', name: 'PPG Industries, Inc.', basePrice: 104, category: 'consumer' },
  { ticker: 'PRGO', name: 'Perrigo Company plc', basePrice: 14, category: 'consumer' },
  { ticker: 'PSA', name: 'Public Storage', basePrice: 261, category: 'consumer' },
  { ticker: 'PSKY', name: 'Paramount Skydance Corporation', basePrice: 13, category: 'consumer' },
  { ticker: 'PTC', name: 'PTC Inc.', basePrice: 175, category: 'consumer' },
  { ticker: 'R', name: 'Ryder System, Inc.', basePrice: 192, category: 'consumer' },
  { ticker: 'REG', name: 'Regency Centers Corporation', basePrice: 70, category: 'consumer' },
  { ticker: 'RHI', name: 'Robert Half Inc.', basePrice: 27, category: 'consumer' },
  { ticker: 'RIG', name: 'Transocean Ltd.', basePrice: 4, category: 'consumer' },
  { ticker: 'RVTY', name: 'Revvity, Inc.', basePrice: 97, category: 'consumer' },
  { ticker: 'S', name: 'SentinelOne, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'SATS', name: 'EchoStar Corporation', basePrice: 109, category: 'consumer' },
  { ticker: 'SBAC', name: 'SBA Communications Corporation', basePrice: 195, category: 'consumer' },
  { ticker: 'SCG', name: 'SCANA Corporation', basePrice: 48, category: 'consumer' },
  { ticker: 'SE', name: 'Sea Limited', basePrice: 128, category: 'consumer' },
  { ticker: 'SHW', name: 'The Sherwin-Williams Company', basePrice: 326, category: 'consumer' },
  { ticker: 'SIG', name: 'Signet Jewelers Limited', basePrice: 83, category: 'consumer' },
  { ticker: 'SII', name: 'Sprott Inc.', basePrice: 98, category: 'consumer' },
  { ticker: 'SLE', name: 'Super League Enterprise, Inc.', basePrice: 7, category: 'consumer' },
  { ticker: 'SLM', name: 'SLM Corporation', basePrice: 27, category: 'consumer' },
  { ticker: 'SNDK', name: 'Sandisk Corporation', basePrice: 240, category: 'consumer' },
  { ticker: 'SOLS', name: 'Solstice Advanced Materials, Inc.', basePrice: 49, category: 'consumer' },
  { ticker: 'SOLV', name: 'Solventum Corporation', basePrice: 80, category: 'consumer' },
  { ticker: 'SPB', name: 'Spectrum Brands Holdings, Inc.', basePrice: 59, category: 'consumer' },
  { ticker: 'SPG', name: 'Simon Property Group, Inc.', basePrice: 187, category: 'consumer' },
  { ticker: 'SUN', name: 'Sunoco LP', basePrice: 52, category: 'consumer' },
  { ticker: 'SVU', name: 'SUPERVALU INC.', basePrice: 32, category: 'consumer' },
  { ticker: 'SW', name: 'Smurfit Westrock Plc', basePrice: 38, category: 'consumer' },
  { ticker: 'SWK', name: 'Stanley Black & Decker, Inc.', basePrice: 75, category: 'consumer' },
  { ticker: 'T', name: 'AT&T Inc.', basePrice: 25, category: 'consumer' },
  { ticker: 'TEG', name: 'TEG', basePrice: 15100, category: 'consumer' },
  { ticker: 'TEL', name: 'TE Connectivity plc', basePrice: 230, category: 'consumer' },
  { ticker: 'TGNA', name: 'TEGNA Inc.', basePrice: 19, category: 'consumer' },
  { ticker: 'TKO', name: 'TKO Group Holdings, Inc.', basePrice: 213, category: 'consumer' },
  { ticker: 'TMUS', name: 'T-Mobile US, Inc.', basePrice: 204, category: 'consumer' },
  { ticker: 'TPL', name: 'Texas Pacific Land Corporation', basePrice: 293, category: 'consumer' },
  { ticker: 'TRIP', name: 'Tripadvisor, Inc.', basePrice: 15, category: 'consumer' },
  { ticker: 'TRMB', name: 'Trimble Inc.', basePrice: 80, category: 'consumer' },
  { ticker: 'TSCO', name: 'Tractor Supply Company', basePrice: 50, category: 'consumer' },
  { ticker: 'TTD', name: 'The Trade Desk, Inc.', basePrice: 38, category: 'consumer' },
  { ticker: 'UA', name: 'Under Armour, Inc.', basePrice: 5, category: 'consumer' },
  { ticker: 'UDR', name: 'UDR, Inc.', basePrice: 37, category: 'consumer' },
  { ticker: 'UNM', name: 'Unum Group', basePrice: 78, category: 'consumer' },
  { ticker: 'URBN', name: 'Urban Outfitters, Inc.', basePrice: 75, category: 'consumer' },
  { ticker: 'VLTO', name: 'Veralto Corporation', basePrice: 101, category: 'consumer' },
  { ticker: 'VNT', name: 'Vontier Corporation', basePrice: 38, category: 'consumer' },
  { ticker: 'VRT', name: 'Vertiv Holdings Co', basePrice: 164, category: 'consumer' },
  { ticker: 'VTR', name: 'Ventas, Inc.', basePrice: 78, category: 'consumer' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', basePrice: 40, category: 'consumer' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery, Inc.', basePrice: 29, category: 'consumer' },
  { ticker: 'WELL', name: 'Welltower Inc.', basePrice: 188, category: 'consumer' },
  { ticker: 'WSM', name: 'Williams-Sonoma, Inc.', basePrice: 181, category: 'consumer' },
  { ticker: 'WU', name: 'The Western Union Company', basePrice: 9, category: 'consumer' },
  { ticker: 'WY', name: 'Weyerhaeuser Company', basePrice: 24, category: 'consumer' },
  { ticker: 'XRX', name: 'Xerox Holdings Corporation', basePrice: 2, category: 'consumer' },
  { ticker: 'XYZ', name: 'Block, Inc.', basePrice: 66, category: 'consumer' },
  { ticker: 'ZION', name: 'Zions Bancorporation, National Association', basePrice: 59, category: 'consumer' },
  { ticker: 'ANDV', name: 'Andeavor', basePrice: 154, category: 'energy' },
  { ticker: 'BTU', name: 'Peabody Energy Corporation', basePrice: 30, category: 'energy' },
  { ticker: 'CPWR', name: 'Ocean Thermal Energy Corporation', basePrice: 50, category: 'energy' },
  { ticker: 'CVE', name: 'Cenovus Energy Inc.', basePrice: 17, category: 'energy' },
  { ticker: 'EP', name: 'Empire Petroleum Corporation', basePrice: 3, category: 'energy' },
  { ticker: 'EXE', name: 'Expand Energy Corporation', basePrice: 111, category: 'energy' },
  { ticker: 'IMO', name: 'Imperial Oil Limited', basePrice: 87, category: 'energy' },
  { ticker: 'MUR', name: 'Murphy Oil Corporation', basePrice: 31, category: 'energy' },
  { ticker: 'NRG', name: 'NRG Energy, Inc.', basePrice: 160, category: 'energy' },
  { ticker: 'NWE', name: 'NorthWestern Energy Group, Inc.', basePrice: 65, category: 'energy' },
  { ticker: 'OGE', name: 'OGE Energy Corp.', basePrice: 43, category: 'energy' },
  { ticker: 'SU', name: 'Suncor Energy Inc.', basePrice: 44, category: 'energy' },
  { ticker: 'TE', name: 'T1 Energy Inc.', basePrice: 6, category: 'energy' },
  { ticker: 'TRP', name: 'TC Energy Corporation', basePrice: 56, category: 'energy' },
  { ticker: 'ACGL', name: 'Arch Capital Group Ltd.', basePrice: 97, category: 'finance' },
  { ticker: 'AIZ', name: 'Assurant, Inc.', basePrice: 242, category: 'finance' },
  { ticker: 'AMG', name: 'Affiliated Managers Group, Inc.', basePrice: 290, category: 'finance' },
  { ticker: 'BHF', name: 'Brighthouse Financial, Inc.', basePrice: 65, category: 'finance' },
  { ticker: 'BR', name: 'Broadridge Financial Solutions, Inc.', basePrice: 224, category: 'finance' },
  { ticker: 'CPT', name: 'Camden Property Trust', basePrice: 111, category: 'finance' },
  { ticker: 'DLR', name: 'Digital Realty Trust, Inc.', basePrice: 156, category: 'finance' },
  { ticker: 'ESS', name: 'Essex Property Trust, Inc.', basePrice: 261, category: 'finance' },
  { ticker: 'FNF', name: 'Fidelity National Financial, Inc.', basePrice: 55, category: 'finance' },
  { ticker: 'FRT', name: 'Federal Realty Investment Trust', basePrice: 101, category: 'finance' },
  { ticker: 'GNW', name: 'Genworth Financial, Inc.', basePrice: 9, category: 'finance' },
  { ticker: 'JEF', name: 'Jefferies Financial Group Inc.', basePrice: 62, category: 'finance' },
  { ticker: 'NSM', name: 'Nationstar Mortgage Holdings Inc.', basePrice: 18, category: 'finance' },
  { ticker: 'SBNY', name: 'Signature Bank', basePrice: 1, category: 'finance' },
  { ticker: 'STI', name: 'Solidion Technology, Inc.', basePrice: 8, category: 'finance' },
  { ticker: 'USL', name: 'United States 12 Month Oil Fund, LP', basePrice: 34, category: 'finance' },
  { ticker: 'VNO', name: 'Vornado Realty Trust', basePrice: 34, category: 'finance' },
  { ticker: 'WB', name: 'Weibo Corporation', basePrice: 10, category: 'finance' },
  { ticker: 'ADCT', name: 'ADC Therapeutics SA', basePrice: 4, category: 'healthcare' },
  { ticker: 'AET', name: 'Aetna Inc.', basePrice: 213, category: 'healthcare' },
  { ticker: 'BEAM', name: 'Beam Therapeutics Inc.', basePrice: 28, category: 'healthcare' },
  { ticker: 'DOC', name: 'Healthpeak Properties, Inc.', basePrice: 16, category: 'healthcare' },
  { ticker: 'DYN', name: 'Dyne Therapeutics, Inc.', basePrice: 19, category: 'healthcare' },
  { ticker: 'EVHC', name: 'Envision Healthcare Corporation', basePrice: 46, category: 'healthcare' },
  { ticker: 'GEHC', name: 'GE HealthCare Technologies Inc.', basePrice: 83, category: 'healthcare' },
  { ticker: 'Jazz', name: 'Jazz Pharmaceuticals plc', basePrice: 171, category: 'healthcare' },
  { ticker: 'MHS', name: 'Morningstar US Healthcare', basePrice: 15893, category: 'healthcare' },
  { ticker: 'NKTR', name: 'Nektar Therapeutics', basePrice: 42, category: 'healthcare' },
  { ticker: 'THC', name: 'Tenet Healthcare Corporation', basePrice: 201, category: 'healthcare' },
  { ticker: 'WST', name: 'West Pharmaceutical Services, Inc.', basePrice: 277, category: 'healthcare' },
  { ticker: 'ZBH', name: 'Zimmer Biomet Holdings, Inc.', basePrice: 91, category: 'healthcare' },
  { ticker: 'AA', name: 'Alcoa Corporation', basePrice: 54, category: 'materials' },
  { ticker: 'ALB', name: 'Albemarle Corporation', basePrice: 142, category: 'materials' },
  { ticker: 'AMCR', name: 'Amcor plc', basePrice: 42, category: 'materials' },
  { ticker: 'APD', name: 'Air Products and Chemicals, Inc.', basePrice: 247, category: 'materials' },
  { ticker: 'AVY', name: 'Avery Dennison Corporation', basePrice: 183, category: 'materials' },
  { ticker: 'BALL', name: 'Ball Corporation', basePrice: 53, category: 'materials' },
  { ticker: 'BMS', name: 'Bemis Company, Inc.', basePrice: 57, category: 'materials' },
  { ticker: 'CCK', name: 'Crown Holdings, Inc.', basePrice: 103, category: 'materials' },
  { ticker: 'CE', name: 'Celanese Corporation', basePrice: 43, category: 'materials' },
  { ticker: 'CF', name: 'CF Industries Holdings, Inc.', basePrice: 77, category: 'materials' },
  { ticker: 'CLF', name: 'Cleveland-Cliffs Inc.', basePrice: 13, category: 'materials' },
  { ticker: 'DD', name: 'DuPont de Nemours, Inc.', basePrice: 41, category: 'materials' },
  { ticker: 'EMN', name: 'Eastman Chemical Company', basePrice: 64, category: 'materials' },
  { ticker: 'FMC', name: 'FMC Corporation', basePrice: 14, category: 'materials' },
  { ticker: 'HUN', name: 'Huntsman Corporation', basePrice: 10, category: 'materials' },
  { ticker: 'IFF', name: 'International Flavors & Fragrances Inc.', basePrice: 68, category: 'materials' },
  { ticker: 'LYB', name: 'LyondellBasell Industries N.V.', basePrice: 44, category: 'materials' },
  { ticker: 'MOS', name: 'The Mosaic Company', basePrice: 24, category: 'materials' },
  { ticker: 'NTR', name: 'Nutrien Ltd.', basePrice: 62, category: 'materials' },
  { ticker: 'OI', name: 'O-I Glass, Inc.', basePrice: 15, category: 'materials' },
  { ticker: 'TMC', name: 'TMC the metals company Inc.', basePrice: 6, category: 'materials' },
  { ticker: 'AIV', name: 'Apartment Investment and Management Company', basePrice: 6, category: 'realestate' },
  { ticker: 'AMT', name: 'American Tower Corporation', basePrice: 177, category: 'realestate' },
  { ticker: 'ARE', name: 'Alexandria Real Estate Equities, Inc.', basePrice: 49, category: 'realestate' },
  { ticker: 'KIM', name: 'Kimco Realty Corporation', basePrice: 20, category: 'realestate' },
  { ticker: 'MAA', name: 'Mid-America Apartment Communities, Inc.', basePrice: 138, category: 'realestate' },
  { ticker: 'O', name: 'Realty Income Corporation', basePrice: 57, category: 'realestate' },
  { ticker: 'SLG', name: 'SL Green Realty Corp.', basePrice: 46, category: 'realestate' },
  { ticker: 'VICI', name: 'VICI Properties Inc.', basePrice: 28, category: 'realestate' },
  { ticker: 'ADP', name: 'Automatic Data Processing, Inc.', basePrice: 260, category: 'tech' },
  { ticker: 'ANET', name: 'Arista Networks, Inc.', basePrice: 132, category: 'tech' },
  { ticker: 'CA', name: 'Xtrackers California Municipal Bond ETF', basePrice: 25, category: 'tech' },
  { ticker: 'CTSH', name: 'Cognizant Technology Solutions Corporation', basePrice: 84, category: 'tech' },
  { ticker: 'DXC', name: 'DXC Technology Company', basePrice: 15, category: 'tech' },
  { ticker: 'EA', name: 'Electronic Arts Inc.', basePrice: 204, category: 'tech' },
  { ticker: 'FDS', name: 'FactSet Research Systems Inc.', basePrice: 290, category: 'tech' },
  { ticker: 'FIX', name: 'Comfort Systems USA, Inc.', basePrice: 946, category: 'tech' },
  { ticker: 'LUMN', name: 'Lumen Technologies, Inc.', basePrice: 8, category: 'tech' },
  { ticker: 'PAYC', name: 'Paycom Software, Inc.', basePrice: 160, category: 'tech' },
  { ticker: 'Q', name: 'Qnity Electronics, Inc.', basePrice: 84, category: 'tech' },
  { ticker: 'SEDG', name: 'SolarEdge Technologies, Inc.', basePrice: 29, category: 'tech' },
  { ticker: 'SHLD', name: 'Global X Defense Tech ETF', basePrice: 65, category: 'tech' },
  { ticker: 'TDC', name: 'Teradata Corporation', basePrice: 31, category: 'tech' },
  { ticker: 'TTWO', name: 'Take-Two Interactive Software, Inc.', basePrice: 258, category: 'tech' },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.', basePrice: 82, category: 'tech' },
